framework:
    cache:
        prefix_seed: innovschool/bulletin
        app: cache.adapter.filesystem
        system: cache.adapter.filesystem
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
