<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260530002224 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admission_reductions (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, school_class_period_id INT NOT NULL, school_period_id INT NOT NULL, student_id INT NOT NULL, reduction_modal_id INT NOT NULL, requested_by_id INT DEFAULT NULL, approved_by_id INT DEFAULT NULL, reduction_amount BIGINT NOT NULL, date_created DATETIME NOT NULL, date_updated DATETIME NOT NULL, pending_approval TINYINT(1) DEFAULT 1 NOT NULL, approval_owners JSON DEFAULT NULL, approved TINYINT(1) DEFAULT 0 NOT NULL, INDEX IDX_BA9FE4EBC32A47EE (school_id), INDEX IDX_BA9FE4EB19F13D4D (school_class_period_id), INDEX IDX_BA9FE4EB9DC4B963 (school_period_id), INDEX IDX_BA9FE4EBCB944F1A (student_id), INDEX IDX_BA9FE4EB8373D28E (reduction_modal_id), INDEX IDX_BA9FE4EB4DA1E751 (requested_by_id), INDEX IDX_BA9FE4EB2D234F6A (approved_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE app_license (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, licence_start_at DATETIME NOT NULL, licence_duration INT DEFAULT 30 NOT NULL, licence_amount INT DEFAULT 0 NOT NULL, license_hash VARCHAR(255) NOT NULL, enabled TINYINT(1) DEFAULT 0 NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', license_type VARCHAR(20) DEFAULT \'trial\' NOT NULL, INDEX IDX_BA357454C32A47EE (school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE class_occurence (id INT AUTO_INCREMENT NOT NULL, classe_id INT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_F7257B15E237E06 (name), INDEX IDX_F7257B18F5EA509 (classe_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE class_subject_module (id BIGINT AUTO_INCREMENT NOT NULL, subject_id INT NOT NULL, class_id INT NOT NULL, period_id INT NOT NULL, module_id INT NOT NULL, school_id INT NOT NULL, module_notation DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_42B3F1CB23EDC87 (subject_id), INDEX IDX_42B3F1CBEA000B10 (class_id), INDEX IDX_42B3F1CBEC8B7ADE (period_id), INDEX IDX_42B3F1CBAFC2B591 (module_id), INDEX IDX_42B3F1CBC32A47EE (school_id), UNIQUE INDEX UNIQ_42B3F1CB23EDC87EA000B10EC8B7ADEC32A47EEAFC2B591 (subject_id, class_id, period_id, school_id, module_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classe (id INT AUTO_INCREMENT NOT NULL, study_level_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8F87BF965E237E06 (name), INDEX IDX_8F87BF96FC385E2E (study_level_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE core_update (id INT AUTO_INCREMENT NOT NULL, version VARCHAR(10) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE evaluation (id INT AUTO_INCREMENT NOT NULL, student_id INT NOT NULL, class_subject_module_id BIGINT NOT NULL, time_id INT NOT NULL, evaluation_note DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_1323A575CB944F1A (student_id), INDEX IDX_1323A575A4748E19 (class_subject_module_id), INDEX IDX_1323A5755EEADD3B (time_id), UNIQUE INDEX UNIQ_1323A575CB944F1AA4748E195EEADD3B (student_id, class_subject_module_id, time_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE evaluation_appreciation_bareme (id INT AUTO_INCREMENT NOT NULL, evaluation_appreciation_template_id INT NOT NULL, evaluation_appreciation_max_note BIGINT NOT NULL, evaluation_appreciation_value VARCHAR(255) NOT NULL, evaluation_appreciation_full_value VARCHAR(255) NOT NULL, INDEX IDX_B228E2A73438EEE9 (evaluation_appreciation_template_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE evaluation_appreciation_template (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_33BE5B325E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fees (id INT AUTO_INCREMENT NOT NULL, amount DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE migration_log (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, source_period_id INT NOT NULL, target_period_id INT NOT NULL, passing_grade DOUBLE PRECISION NOT NULL, options JSON NOT NULL, created_ids JSON NOT NULL, status VARCHAR(20) NOT NULL, executed_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', executed_by VARCHAR(255) NOT NULL, config_summary JSON NOT NULL, student_stats JSON NOT NULL, INDEX IDX_399FA51EC32A47EE (school_id), INDEX IDX_399FA51E8415E910 (source_period_id), INDEX IDX_399FA51ED83F08F2 (target_period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE modalities_subscriptions (id INT AUTO_INCREMENT NOT NULL, student_id INT NOT NULL, school_class_period_id INT NOT NULL, school_period_id INT NOT NULL, payment_modal_id INT NOT NULL, subscription_date DATETIME NOT NULL, enabled TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, is_full TINYINT(1) DEFAULT 0 NOT NULL, is_full_period VARCHAR(20) DEFAULT NULL, INDEX IDX_6582079CCB944F1A (student_id), INDEX IDX_6582079C19F13D4D (school_class_period_id), INDEX IDX_6582079C9DC4B963 (school_period_id), INDEX IDX_6582079CCC33534F (payment_modal_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE module (name VARCHAR(50) NOT NULL, enabled TINYINT(1) NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operation_logs (id INT AUTO_INCREMENT NOT NULL, operation_type VARCHAR(255) NOT NULL, entity_name VARCHAR(255) DEFAULT NULL, entity_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, error_message LONGTEXT DEFAULT NULL, timestamp DATETIME NOT NULL, performed_by VARCHAR(255) NOT NULL, additional_data LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment (id INT AUTO_INCREMENT NOT NULL, author_id INT DEFAULT NULL, fees_id INT DEFAULT NULL, amount DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL, for_month DATE NOT NULL, INDEX IDX_6D28840DF675F31B (author_id), INDEX IDX_6D28840D9C6BD325 (fees_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE registration_card_base_config (id INT AUTO_INCREMENT NOT NULL, card_header VARCHAR(255) NOT NULL, national_motto VARCHAR(255) NOT NULL, head_officer_sign VARCHAR(255) NOT NULL, card_bg VARCHAR(255) NOT NULL, sign_title VARCHAR(255) DEFAULT NULL, card_header_a VARCHAR(255) DEFAULT NULL, national_motto_a VARCHAR(255) DEFAULT NULL, double_header_layout TINYINT(1) DEFAULT 0 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE report_card_template (id INT AUTO_INCREMENT NOT NULL, evaluation_appreciation_template_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(1024) DEFAULT NULL, header_left LONGTEXT DEFAULT NULL, header_right LONGTEXT DEFAULT NULL, national_motto_left VARCHAR(255) DEFAULT NULL, national_motto_right VARCHAR(255) DEFAULT NULL, header_title VARCHAR(255) DEFAULT NULL, additional_header_left LONGTEXT DEFAULT NULL, additional_header_right LONGTEXT DEFAULT NULL, school_values_left LONGTEXT DEFAULT NULL, school_values_right LONGTEXT DEFAULT NULL, INDEX IDX_A78C90703438EEE9 (evaluation_appreciation_template_id), UNIQUE INDEX unique_report_card_template_name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school (id INT AUTO_INCREMENT NOT NULL, registration_base_config_id INT DEFAULT NULL, evaluation_appreciation_template_id INT DEFAULT NULL, report_card_template_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, address LONGTEXT NOT NULL, contact_name VARCHAR(255) NOT NULL, contact_phone VARCHAR(255) DEFAULT NULL, contact_email VARCHAR(255) NOT NULL, logo VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, last_acces_at DATETIME NOT NULL, customer TINYINT(1) NOT NULL, acronym VARCHAR(255) NOT NULL, school_number VARCHAR(255) NOT NULL, license_hash VARCHAR(255) DEFAULT NULL, admin_only TINYINT(1) DEFAULT 0 NOT NULL, school_values LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_F99EDABB6B2C1C98 (school_number), UNIQUE INDEX UNIQ_F99EDABBB069795C (registration_base_config_id), INDEX IDX_F99EDABB3438EEE9 (evaluation_appreciation_template_id), INDEX IDX_F99EDABBA7FFE8D6 (report_card_template_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_class_admission_payments (id INT AUTO_INCREMENT NOT NULL, school_class_period_id INT NOT NULL, student_id INT NOT NULL, school_id INT NOT NULL, school_period_id INT NOT NULL, payment_modal_id INT NOT NULL, payment_date DATETIME NOT NULL, payment_amount BIGINT DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, modal_type VARCHAR(20) NOT NULL, INDEX IDX_33FDA22319F13D4D (school_class_period_id), INDEX IDX_33FDA223CB944F1A (student_id), INDEX IDX_33FDA223C32A47EE (school_id), INDEX IDX_33FDA2239DC4B963 (school_period_id), INDEX IDX_33FDA223CC33534F (payment_modal_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_class_attendance (id INT AUTO_INCREMENT NOT NULL, evaluation_id INT DEFAULT NULL, school_class_period_id INT DEFAULT NULL, attendanc_json JSON NOT NULL, INDEX IDX_410B528456C5646 (evaluation_id), INDEX IDX_410B52819F13D4D (school_class_period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_class_numbering_type (id INT AUTO_INCREMENT NOT NULL, classe_id INT NOT NULL, school_id INT NOT NULL, numbering_type VARCHAR(20) NOT NULL, INDEX IDX_D035AC5E8F5EA509 (classe_id), INDEX IDX_D035AC5EC32A47EE (school_id), UNIQUE INDEX unique_numbering_type (classe_id, school_id, numbering_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_class_payment_modals (id INT AUTO_INCREMENT NOT NULL, school_class_period_id INT DEFAULT NULL, school_period_id INT NOT NULL, school_id INT NOT NULL, label VARCHAR(255) NOT NULL, amount BIGINT NOT NULL, due_date DATE NOT NULL, modal_type VARCHAR(20) NOT NULL, modal_priority INT DEFAULT 0 NOT NULL, INDEX IDX_662FC67919F13D4D (school_class_period_id), INDEX IDX_662FC6799DC4B963 (school_period_id), INDEX IDX_662FC679C32A47EE (school_id), UNIQUE INDEX unique_class_school_period (school_class_period_id, school_id, school_period_id, modal_type, label), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_class_period (id INT AUTO_INCREMENT NOT NULL, school_id INT DEFAULT NULL, period_id INT DEFAULT NULL, evaluation_appreciation_template_id INT DEFAULT NULL, class_master_id INT DEFAULT NULL, report_card_template_id INT DEFAULT NULL, class_occurence_id INT DEFAULT NULL, INDEX IDX_C1D6E9C8C32A47EE (school_id), INDEX IDX_C1D6E9C8EC8B7ADE (period_id), INDEX IDX_C1D6E9C83438EEE9 (evaluation_appreciation_template_id), INDEX IDX_C1D6E9C8786C442E (class_master_id), INDEX IDX_C1D6E9C8A7FFE8D6 (report_card_template_id), INDEX IDX_C1D6E9C8E92C8A9B (class_occurence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_class_subject (id INT AUTO_INCREMENT NOT NULL, school_class_period_id INT NOT NULL, study_subject_id INT NOT NULL, group_id INT DEFAULT NULL, teacher_id INT DEFAULT NULL, section_category_subject_id INT DEFAULT NULL, coefficient INT DEFAULT 1 NOT NULL, awaited_skills LONGTEXT DEFAULT NULL, INDEX IDX_12A9F5B819F13D4D (school_class_period_id), INDEX IDX_12A9F5B885A2B8E7 (study_subject_id), INDEX IDX_12A9F5B8FE54D947 (group_id), INDEX IDX_12A9F5B841807E1D (teacher_id), INDEX IDX_12A9F5B87A1E0799 (section_category_subject_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_class_subject_evaluation_time_not_applicable (id INT AUTO_INCREMENT NOT NULL, school_class_subject_id INT NOT NULL, school_evaluation_time_id INT NOT NULL, not_applicable TINYINT(1) NOT NULL, INDEX IDX_C8CD1AA56BCD643E (school_class_subject_id), INDEX IDX_C8CD1AA542C6795B (school_evaluation_time_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_evaluation (id INT AUTO_INCREMENT NOT NULL, frame_id INT DEFAULT NULL, time_id INT DEFAULT NULL, period_id INT DEFAULT NULL, creted_at DATETIME NOT NULL, INDEX IDX_A68225873FA3C347 (frame_id), INDEX IDX_A68225875EEADD3B (time_id), INDEX IDX_A6822587EC8B7ADE (period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_evaluation_frame (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, short_name VARCHAR(20) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_evaluation_time (id INT AUTO_INCREMENT NOT NULL, evaluation_frame_id INT DEFAULT NULL, type_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, short_name VARCHAR(20) NOT NULL, INDEX IDX_BC770F5132EDBA61 (evaluation_frame_id), INDEX IDX_BC770F51C54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_evaluation_time_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_95254E7E5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_license_payment (id INT AUTO_INCREMENT NOT NULL, license_id INT NOT NULL, date_payment DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, payment_amount INT DEFAULT 0 NOT NULL, payment_method VARCHAR(100) NOT NULL, INDEX IDX_1A9417FA460F904B (license_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_period (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_section (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, study_level_id INT NOT NULL, INDEX IDX_BF5C4877C32A47EE (school_id), INDEX IDX_BF5C4877FC385E2E (study_level_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_study_type (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, studies_type_id INT NOT NULL, INDEX IDX_46A73FE2C32A47EE (school_id), INDEX IDX_46A73FE2BEE13D92 (studies_type_id), UNIQUE INDEX unique_school_studies_type (school_id, studies_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE section_category_subject (id INT AUTO_INCREMENT NOT NULL, section_category_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_DC5615E04B7E29D (section_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE student_attendance (id INT AUTO_INCREMENT NOT NULL, student_id INT DEFAULT NULL, school_class_period_id INT DEFAULT NULL, abscence INT NOT NULL, INDEX IDX_803CE070CB944F1A (student_id), INDEX IDX_803CE07019F13D4D (school_class_period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE student_class (id INT AUTO_INCREMENT NOT NULL, student_id INT DEFAULT NULL, school_class_period_id INT DEFAULT NULL, INDEX IDX_657C6002CB944F1A (student_id), INDEX IDX_657C600219F13D4D (school_class_period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE student_class_attendance (id INT AUTO_INCREMENT NOT NULL, student_class_id INT NOT NULL, time_id INT NOT NULL, heures_absence INT DEFAULT 0 NOT NULL, absences_justifiee INT DEFAULT 0 NOT NULL, retard INT DEFAULT 0 NOT NULL, retard_injustifie INT DEFAULT 0 NOT NULL, retenue INT DEFAULT 0 NOT NULL, avertissement_discipline INT DEFAULT 0 NOT NULL, blame INT DEFAULT 0 NOT NULL, jour_exclusion INT DEFAULT 0 NOT NULL, exclusion_definitive TINYINT(1) DEFAULT 0 NOT NULL, INDEX IDX_9BFDE46598B478B (student_class_id), INDEX IDX_9BFDE465EEADD3B (time_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE student_class_timetable_presence (id INT AUTO_INCREMENT NOT NULL, student_class_id INT NOT NULL, time_table_slot_id INT NOT NULL, school_evaluation_time_id INT NOT NULL, status VARCHAR(10) NOT NULL, date_presence DATE NOT NULL, locked TINYINT(1) DEFAULT 0 NOT NULL, INDEX IDX_5F468408598B478B (student_class_id), INDEX IDX_5F468408D307021C (time_table_slot_id), INDEX IDX_5F46840842C6795B (school_evaluation_time_id), UNIQUE INDEX unique_presence_per_studentclass_slot_datepresence (student_class_id, time_table_slot_id, date_presence), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE studies_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_FB505DFC5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE study_level (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE study_subject (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX UNIQ_CEDBC3185E237E06 (name), UNIQUE INDEX UNIQ_CEDBC318989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subject_group (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, period_id INT NOT NULL, pos_order INT NOT NULL, description VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_7C53851D6DE44026 (description), INDEX IDX_7C53851DC32A47EE (school_id), INDEX IDX_7C53851DEC8B7ADE (period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subjects_modules (id INT AUTO_INCREMENT NOT NULL, module_name VARCHAR(255) NOT NULL, module_slug VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_6479375E41F3B0A (module_name), UNIQUE INDEX UNIQ_647937522A1DE6E (module_slug), UNIQUE INDEX UNIQ_6479375E41F3B0A22A1DE6E (module_name, module_slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE timetable (id INT AUTO_INCREMENT NOT NULL, teacher_id INT NOT NULL, school_id INT NOT NULL, period_id INT NOT NULL, label VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_6B1F670EA750E8 (label), INDEX IDX_6B1F67041807E1D (teacher_id), INDEX IDX_6B1F670C32A47EE (school_id), INDEX IDX_6B1F670EC8B7ADE (period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE timetable_day (id INT AUTO_INCREMENT NOT NULL, timetable_id INT NOT NULL, day_of_week INT NOT NULL, INDEX IDX_6600A558CC306847 (timetable_id), UNIQUE INDEX unique_timetable_day (timetable_id, day_of_week), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE timetable_slot (id INT AUTO_INCREMENT NOT NULL, timetable_day_id INT NOT NULL, subject_id INT NOT NULL, school_class_period_id INT NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL, notes LONGTEXT DEFAULT NULL, INDEX IDX_3932CA69D79EF2F2 (timetable_day_id), INDEX IDX_3932CA6923EDC87 (subject_id), INDEX IDX_3932CA6919F13D4D (school_class_period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, school_id INT DEFAULT NULL, tutor_id INT DEFAULT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, address LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, enabled TINYINT(1) NOT NULL, full_name VARCHAR(255) NOT NULL, login_at DATETIME DEFAULT NULL, capacity JSON DEFAULT NULL, infos LONGTEXT DEFAULT NULL, gender VARCHAR(10) NOT NULL, repeated TINYINT(1) NOT NULL, registration_number VARCHAR(255) DEFAULT NULL, national_registration_number VARCHAR(255) DEFAULT NULL, date_of_birth DATE DEFAULT NULL, religion VARCHAR(255) DEFAULT NULL, place_of_birth VARCHAR(255) DEFAULT NULL, photo VARCHAR(255) DEFAULT NULL, reset_password TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_8D93D64938CEDFBE (registration_number), UNIQUE INDEX UNIQ_8D93D64971D0A9E8 (national_registration_number), INDEX IDX_8D93D649C32A47EE (school_id), INDEX IDX_8D93D649208F64F1 (tutor_id), UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_base_configuration (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, school_id INT NOT NULL, class_list JSON NOT NULL, section_list JSON NOT NULL, INDEX IDX_811D7695A76ED395 (user_id), INDEX IDX_811D7695C32A47EE (school_id), UNIQUE INDEX unique_user_school (user_id, school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EBC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EB19F13D4D FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id)');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EB9DC4B963 FOREIGN KEY (school_period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EBCB944F1A FOREIGN KEY (student_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EB8373D28E FOREIGN KEY (reduction_modal_id) REFERENCES school_class_payment_modals (id)');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EB4DA1E751 FOREIGN KEY (requested_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EB2D234F6A FOREIGN KEY (approved_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE app_license ADD CONSTRAINT FK_BA357454C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE class_occurence ADD CONSTRAINT FK_F7257B18F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id)');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT FK_42B3F1CB23EDC87 FOREIGN KEY (subject_id) REFERENCES study_subject (id)');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT FK_42B3F1CBEA000B10 FOREIGN KEY (class_id) REFERENCES school_class_period (id)');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT FK_42B3F1CBEC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT FK_42B3F1CBAFC2B591 FOREIGN KEY (module_id) REFERENCES subjects_modules (id)');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT FK_42B3F1CBC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE classe ADD CONSTRAINT FK_8F87BF96FC385E2E FOREIGN KEY (study_level_id) REFERENCES study_level (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575CB944F1A FOREIGN KEY (student_id) REFERENCES student_class (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575A4748E19 FOREIGN KEY (class_subject_module_id) REFERENCES class_subject_module (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A5755EEADD3B FOREIGN KEY (time_id) REFERENCES school_evaluation_time (id)');
        $this->addSql('ALTER TABLE evaluation_appreciation_bareme ADD CONSTRAINT FK_B228E2A73438EEE9 FOREIGN KEY (evaluation_appreciation_template_id) REFERENCES evaluation_appreciation_template (id)');
        $this->addSql('ALTER TABLE migration_log ADD CONSTRAINT FK_399FA51EC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE migration_log ADD CONSTRAINT FK_399FA51E8415E910 FOREIGN KEY (source_period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE migration_log ADD CONSTRAINT FK_399FA51ED83F08F2 FOREIGN KEY (target_period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE modalities_subscriptions ADD CONSTRAINT FK_6582079CCB944F1A FOREIGN KEY (student_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE modalities_subscriptions ADD CONSTRAINT FK_6582079C19F13D4D FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id)');
        $this->addSql('ALTER TABLE modalities_subscriptions ADD CONSTRAINT FK_6582079C9DC4B963 FOREIGN KEY (school_period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE modalities_subscriptions ADD CONSTRAINT FK_6582079CCC33534F FOREIGN KEY (payment_modal_id) REFERENCES school_class_payment_modals (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DF675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D9C6BD325 FOREIGN KEY (fees_id) REFERENCES fees (id)');
        $this->addSql('ALTER TABLE report_card_template ADD CONSTRAINT FK_A78C90703438EEE9 FOREIGN KEY (evaluation_appreciation_template_id) REFERENCES evaluation_appreciation_template (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABBB069795C FOREIGN KEY (registration_base_config_id) REFERENCES registration_card_base_config (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABB3438EEE9 FOREIGN KEY (evaluation_appreciation_template_id) REFERENCES evaluation_appreciation_template (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABBA7FFE8D6 FOREIGN KEY (report_card_template_id) REFERENCES report_card_template (id)');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA22319F13D4D FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id)');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA223CB944F1A FOREIGN KEY (student_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA223C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA2239DC4B963 FOREIGN KEY (school_period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA223CC33534F FOREIGN KEY (payment_modal_id) REFERENCES school_class_payment_modals (id)');
        $this->addSql('ALTER TABLE school_class_attendance ADD CONSTRAINT FK_410B528456C5646 FOREIGN KEY (evaluation_id) REFERENCES school_evaluation (id)');
        $this->addSql('ALTER TABLE school_class_attendance ADD CONSTRAINT FK_410B52819F13D4D FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id)');
        $this->addSql('ALTER TABLE school_class_numbering_type ADD CONSTRAINT FK_D035AC5E8F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id)');
        $this->addSql('ALTER TABLE school_class_numbering_type ADD CONSTRAINT FK_D035AC5EC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_class_payment_modals ADD CONSTRAINT FK_662FC67919F13D4D FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id)');
        $this->addSql('ALTER TABLE school_class_payment_modals ADD CONSTRAINT FK_662FC6799DC4B963 FOREIGN KEY (school_period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE school_class_payment_modals ADD CONSTRAINT FK_662FC679C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_class_period ADD CONSTRAINT FK_C1D6E9C8C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_class_period ADD CONSTRAINT FK_C1D6E9C8EC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE school_class_period ADD CONSTRAINT FK_C1D6E9C83438EEE9 FOREIGN KEY (evaluation_appreciation_template_id) REFERENCES evaluation_appreciation_template (id)');
        $this->addSql('ALTER TABLE school_class_period ADD CONSTRAINT FK_C1D6E9C8786C442E FOREIGN KEY (class_master_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE school_class_period ADD CONSTRAINT FK_C1D6E9C8A7FFE8D6 FOREIGN KEY (report_card_template_id) REFERENCES report_card_template (id)');
        $this->addSql('ALTER TABLE school_class_period ADD CONSTRAINT FK_C1D6E9C8E92C8A9B FOREIGN KEY (class_occurence_id) REFERENCES class_occurence (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT FK_12A9F5B819F13D4D FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT FK_12A9F5B885A2B8E7 FOREIGN KEY (study_subject_id) REFERENCES study_subject (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT FK_12A9F5B8FE54D947 FOREIGN KEY (group_id) REFERENCES subject_group (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT FK_12A9F5B841807E1D FOREIGN KEY (teacher_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT FK_12A9F5B87A1E0799 FOREIGN KEY (section_category_subject_id) REFERENCES section_category_subject (id)');
        $this->addSql('ALTER TABLE school_class_subject_evaluation_time_not_applicable ADD CONSTRAINT FK_C8CD1AA56BCD643E FOREIGN KEY (school_class_subject_id) REFERENCES school_class_subject (id)');
        $this->addSql('ALTER TABLE school_class_subject_evaluation_time_not_applicable ADD CONSTRAINT FK_C8CD1AA542C6795B FOREIGN KEY (school_evaluation_time_id) REFERENCES school_evaluation_time (id)');
        $this->addSql('ALTER TABLE school_evaluation ADD CONSTRAINT FK_A68225873FA3C347 FOREIGN KEY (frame_id) REFERENCES school_evaluation_frame (id)');
        $this->addSql('ALTER TABLE school_evaluation ADD CONSTRAINT FK_A68225875EEADD3B FOREIGN KEY (time_id) REFERENCES school_evaluation_time (id)');
        $this->addSql('ALTER TABLE school_evaluation ADD CONSTRAINT FK_A6822587EC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE school_evaluation_time ADD CONSTRAINT FK_BC770F5132EDBA61 FOREIGN KEY (evaluation_frame_id) REFERENCES school_evaluation_frame (id)');
        $this->addSql('ALTER TABLE school_evaluation_time ADD CONSTRAINT FK_BC770F51C54C8C93 FOREIGN KEY (type_id) REFERENCES school_evaluation_time_type (id)');
        $this->addSql('ALTER TABLE school_license_payment ADD CONSTRAINT FK_1A9417FA460F904B FOREIGN KEY (license_id) REFERENCES app_license (id)');
        $this->addSql('ALTER TABLE school_section ADD CONSTRAINT FK_BF5C4877C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_section ADD CONSTRAINT FK_BF5C4877FC385E2E FOREIGN KEY (study_level_id) REFERENCES study_level (id)');
        $this->addSql('ALTER TABLE school_study_type ADD CONSTRAINT FK_46A73FE2C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_study_type ADD CONSTRAINT FK_46A73FE2BEE13D92 FOREIGN KEY (studies_type_id) REFERENCES studies_type (id)');
        $this->addSql('ALTER TABLE section_category_subject ADD CONSTRAINT FK_DC5615E04B7E29D FOREIGN KEY (section_category_id) REFERENCES classe (id)');
        $this->addSql('ALTER TABLE student_attendance ADD CONSTRAINT FK_803CE070CB944F1A FOREIGN KEY (student_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE student_attendance ADD CONSTRAINT FK_803CE07019F13D4D FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id)');
        $this->addSql('ALTER TABLE student_class ADD CONSTRAINT FK_657C6002CB944F1A FOREIGN KEY (student_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE student_class ADD CONSTRAINT FK_657C600219F13D4D FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id)');
        $this->addSql('ALTER TABLE student_class_attendance ADD CONSTRAINT FK_9BFDE46598B478B FOREIGN KEY (student_class_id) REFERENCES student_class (id)');
        $this->addSql('ALTER TABLE student_class_attendance ADD CONSTRAINT FK_9BFDE465EEADD3B FOREIGN KEY (time_id) REFERENCES school_evaluation_time (id)');
        $this->addSql('ALTER TABLE student_class_timetable_presence ADD CONSTRAINT FK_5F468408598B478B FOREIGN KEY (student_class_id) REFERENCES student_class (id)');
        $this->addSql('ALTER TABLE student_class_timetable_presence ADD CONSTRAINT FK_5F468408D307021C FOREIGN KEY (time_table_slot_id) REFERENCES timetable_slot (id)');
        $this->addSql('ALTER TABLE student_class_timetable_presence ADD CONSTRAINT FK_5F46840842C6795B FOREIGN KEY (school_evaluation_time_id) REFERENCES school_evaluation_time (id)');
        $this->addSql('ALTER TABLE subject_group ADD CONSTRAINT FK_7C53851DC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE subject_group ADD CONSTRAINT FK_7C53851DEC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE timetable ADD CONSTRAINT FK_6B1F67041807E1D FOREIGN KEY (teacher_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE timetable ADD CONSTRAINT FK_6B1F670C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE timetable ADD CONSTRAINT FK_6B1F670EC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE timetable_day ADD CONSTRAINT FK_6600A558CC306847 FOREIGN KEY (timetable_id) REFERENCES timetable (id)');
        $this->addSql('ALTER TABLE timetable_slot ADD CONSTRAINT FK_3932CA69D79EF2F2 FOREIGN KEY (timetable_day_id) REFERENCES timetable_day (id)');
        $this->addSql('ALTER TABLE timetable_slot ADD CONSTRAINT FK_3932CA6923EDC87 FOREIGN KEY (subject_id) REFERENCES study_subject (id)');
        $this->addSql('ALTER TABLE timetable_slot ADD CONSTRAINT FK_3932CA6919F13D4D FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D649C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D649208F64F1 FOREIGN KEY (tutor_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE user_base_configuration ADD CONSTRAINT FK_811D7695A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE user_base_configuration ADD CONSTRAINT FK_811D7695C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EBC32A47EE');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EB19F13D4D');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EB9DC4B963');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EBCB944F1A');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EB8373D28E');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EB4DA1E751');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EB2D234F6A');
        $this->addSql('ALTER TABLE app_license DROP FOREIGN KEY FK_BA357454C32A47EE');
        $this->addSql('ALTER TABLE class_occurence DROP FOREIGN KEY FK_F7257B18F5EA509');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY FK_42B3F1CB23EDC87');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY FK_42B3F1CBEA000B10');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY FK_42B3F1CBEC8B7ADE');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY FK_42B3F1CBAFC2B591');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY FK_42B3F1CBC32A47EE');
        $this->addSql('ALTER TABLE classe DROP FOREIGN KEY FK_8F87BF96FC385E2E');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A575CB944F1A');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A575A4748E19');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A5755EEADD3B');
        $this->addSql('ALTER TABLE evaluation_appreciation_bareme DROP FOREIGN KEY FK_B228E2A73438EEE9');
        $this->addSql('ALTER TABLE migration_log DROP FOREIGN KEY FK_399FA51EC32A47EE');
        $this->addSql('ALTER TABLE migration_log DROP FOREIGN KEY FK_399FA51E8415E910');
        $this->addSql('ALTER TABLE migration_log DROP FOREIGN KEY FK_399FA51ED83F08F2');
        $this->addSql('ALTER TABLE modalities_subscriptions DROP FOREIGN KEY FK_6582079CCB944F1A');
        $this->addSql('ALTER TABLE modalities_subscriptions DROP FOREIGN KEY FK_6582079C19F13D4D');
        $this->addSql('ALTER TABLE modalities_subscriptions DROP FOREIGN KEY FK_6582079C9DC4B963');
        $this->addSql('ALTER TABLE modalities_subscriptions DROP FOREIGN KEY FK_6582079CCC33534F');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840DF675F31B');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D9C6BD325');
        $this->addSql('ALTER TABLE report_card_template DROP FOREIGN KEY FK_A78C90703438EEE9');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABBB069795C');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABB3438EEE9');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABBA7FFE8D6');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA22319F13D4D');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA223CB944F1A');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA223C32A47EE');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA2239DC4B963');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA223CC33534F');
        $this->addSql('ALTER TABLE school_class_attendance DROP FOREIGN KEY FK_410B528456C5646');
        $this->addSql('ALTER TABLE school_class_attendance DROP FOREIGN KEY FK_410B52819F13D4D');
        $this->addSql('ALTER TABLE school_class_numbering_type DROP FOREIGN KEY FK_D035AC5E8F5EA509');
        $this->addSql('ALTER TABLE school_class_numbering_type DROP FOREIGN KEY FK_D035AC5EC32A47EE');
        $this->addSql('ALTER TABLE school_class_payment_modals DROP FOREIGN KEY FK_662FC67919F13D4D');
        $this->addSql('ALTER TABLE school_class_payment_modals DROP FOREIGN KEY FK_662FC6799DC4B963');
        $this->addSql('ALTER TABLE school_class_payment_modals DROP FOREIGN KEY FK_662FC679C32A47EE');
        $this->addSql('ALTER TABLE school_class_period DROP FOREIGN KEY FK_C1D6E9C8C32A47EE');
        $this->addSql('ALTER TABLE school_class_period DROP FOREIGN KEY FK_C1D6E9C8EC8B7ADE');
        $this->addSql('ALTER TABLE school_class_period DROP FOREIGN KEY FK_C1D6E9C83438EEE9');
        $this->addSql('ALTER TABLE school_class_period DROP FOREIGN KEY FK_C1D6E9C8786C442E');
        $this->addSql('ALTER TABLE school_class_period DROP FOREIGN KEY FK_C1D6E9C8A7FFE8D6');
        $this->addSql('ALTER TABLE school_class_period DROP FOREIGN KEY FK_C1D6E9C8E92C8A9B');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY FK_12A9F5B819F13D4D');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY FK_12A9F5B885A2B8E7');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY FK_12A9F5B8FE54D947');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY FK_12A9F5B841807E1D');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY FK_12A9F5B87A1E0799');
        $this->addSql('ALTER TABLE school_class_subject_evaluation_time_not_applicable DROP FOREIGN KEY FK_C8CD1AA56BCD643E');
        $this->addSql('ALTER TABLE school_class_subject_evaluation_time_not_applicable DROP FOREIGN KEY FK_C8CD1AA542C6795B');
        $this->addSql('ALTER TABLE school_evaluation DROP FOREIGN KEY FK_A68225873FA3C347');
        $this->addSql('ALTER TABLE school_evaluation DROP FOREIGN KEY FK_A68225875EEADD3B');
        $this->addSql('ALTER TABLE school_evaluation DROP FOREIGN KEY FK_A6822587EC8B7ADE');
        $this->addSql('ALTER TABLE school_evaluation_time DROP FOREIGN KEY FK_BC770F5132EDBA61');
        $this->addSql('ALTER TABLE school_evaluation_time DROP FOREIGN KEY FK_BC770F51C54C8C93');
        $this->addSql('ALTER TABLE school_license_payment DROP FOREIGN KEY FK_1A9417FA460F904B');
        $this->addSql('ALTER TABLE school_section DROP FOREIGN KEY FK_BF5C4877C32A47EE');
        $this->addSql('ALTER TABLE school_section DROP FOREIGN KEY FK_BF5C4877FC385E2E');
        $this->addSql('ALTER TABLE school_study_type DROP FOREIGN KEY FK_46A73FE2C32A47EE');
        $this->addSql('ALTER TABLE school_study_type DROP FOREIGN KEY FK_46A73FE2BEE13D92');
        $this->addSql('ALTER TABLE section_category_subject DROP FOREIGN KEY FK_DC5615E04B7E29D');
        $this->addSql('ALTER TABLE student_attendance DROP FOREIGN KEY FK_803CE070CB944F1A');
        $this->addSql('ALTER TABLE student_attendance DROP FOREIGN KEY FK_803CE07019F13D4D');
        $this->addSql('ALTER TABLE student_class DROP FOREIGN KEY FK_657C6002CB944F1A');
        $this->addSql('ALTER TABLE student_class DROP FOREIGN KEY FK_657C600219F13D4D');
        $this->addSql('ALTER TABLE student_class_attendance DROP FOREIGN KEY FK_9BFDE46598B478B');
        $this->addSql('ALTER TABLE student_class_attendance DROP FOREIGN KEY FK_9BFDE465EEADD3B');
        $this->addSql('ALTER TABLE student_class_timetable_presence DROP FOREIGN KEY FK_5F468408598B478B');
        $this->addSql('ALTER TABLE student_class_timetable_presence DROP FOREIGN KEY FK_5F468408D307021C');
        $this->addSql('ALTER TABLE student_class_timetable_presence DROP FOREIGN KEY FK_5F46840842C6795B');
        $this->addSql('ALTER TABLE subject_group DROP FOREIGN KEY FK_7C53851DC32A47EE');
        $this->addSql('ALTER TABLE subject_group DROP FOREIGN KEY FK_7C53851DEC8B7ADE');
        $this->addSql('ALTER TABLE timetable DROP FOREIGN KEY FK_6B1F67041807E1D');
        $this->addSql('ALTER TABLE timetable DROP FOREIGN KEY FK_6B1F670C32A47EE');
        $this->addSql('ALTER TABLE timetable DROP FOREIGN KEY FK_6B1F670EC8B7ADE');
        $this->addSql('ALTER TABLE timetable_day DROP FOREIGN KEY FK_6600A558CC306847');
        $this->addSql('ALTER TABLE timetable_slot DROP FOREIGN KEY FK_3932CA69D79EF2F2');
        $this->addSql('ALTER TABLE timetable_slot DROP FOREIGN KEY FK_3932CA6923EDC87');
        $this->addSql('ALTER TABLE timetable_slot DROP FOREIGN KEY FK_3932CA6919F13D4D');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D649C32A47EE');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D649208F64F1');
        $this->addSql('ALTER TABLE user_base_configuration DROP FOREIGN KEY FK_811D7695A76ED395');
        $this->addSql('ALTER TABLE user_base_configuration DROP FOREIGN KEY FK_811D7695C32A47EE');
        $this->addSql('DROP TABLE admission_reductions');
        $this->addSql('DROP TABLE app_license');
        $this->addSql('DROP TABLE class_occurence');
        $this->addSql('DROP TABLE class_subject_module');
        $this->addSql('DROP TABLE classe');
        $this->addSql('DROP TABLE core_update');
        $this->addSql('DROP TABLE evaluation');
        $this->addSql('DROP TABLE evaluation_appreciation_bareme');
        $this->addSql('DROP TABLE evaluation_appreciation_template');
        $this->addSql('DROP TABLE fees');
        $this->addSql('DROP TABLE migration_log');
        $this->addSql('DROP TABLE modalities_subscriptions');
        $this->addSql('DROP TABLE module');
        $this->addSql('DROP TABLE operation_logs');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE registration_card_base_config');
        $this->addSql('DROP TABLE report_card_template');
        $this->addSql('DROP TABLE school');
        $this->addSql('DROP TABLE school_class_admission_payments');
        $this->addSql('DROP TABLE school_class_attendance');
        $this->addSql('DROP TABLE school_class_numbering_type');
        $this->addSql('DROP TABLE school_class_payment_modals');
        $this->addSql('DROP TABLE school_class_period');
        $this->addSql('DROP TABLE school_class_subject');
        $this->addSql('DROP TABLE school_class_subject_evaluation_time_not_applicable');
        $this->addSql('DROP TABLE school_evaluation');
        $this->addSql('DROP TABLE school_evaluation_frame');
        $this->addSql('DROP TABLE school_evaluation_time');
        $this->addSql('DROP TABLE school_evaluation_time_type');
        $this->addSql('DROP TABLE school_license_payment');
        $this->addSql('DROP TABLE school_period');
        $this->addSql('DROP TABLE school_section');
        $this->addSql('DROP TABLE school_study_type');
        $this->addSql('DROP TABLE section_category_subject');
        $this->addSql('DROP TABLE student_attendance');
        $this->addSql('DROP TABLE student_class');
        $this->addSql('DROP TABLE student_class_attendance');
        $this->addSql('DROP TABLE student_class_timetable_presence');
        $this->addSql('DROP TABLE studies_type');
        $this->addSql('DROP TABLE study_level');
        $this->addSql('DROP TABLE study_subject');
        $this->addSql('DROP TABLE subject_group');
        $this->addSql('DROP TABLE subjects_modules');
        $this->addSql('DROP TABLE timetable');
        $this->addSql('DROP TABLE timetable_day');
        $this->addSql('DROP TABLE timetable_slot');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE user_base_configuration');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
