<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260502142745 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649C32A47EE');
        $this->addSql('ALTER TABLE user_base_configuration DROP FOREIGN KEY FK_811D7695C32A47EE');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EBCB944F1A');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EBC32A47EE');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EB9DC4B963');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY admission_reductions_ibfk_3');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EB8373D28E');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EB14463F54');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY admission_reductions_ibfk_2');
        $this->addSql('ALTER TABLE app_license DROP FOREIGN KEY app_license_ibfk_1');
        $this->addSql('ALTER TABLE class_occurence DROP FOREIGN KEY class_occurence_ibfk_1');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY class_subject_module_ibfk_6');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY class_subject_module_ibfk_5');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY class_subject_module_ibfk_3');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY class_subject_module_ibfk_2');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY class_subject_module_ibfk_1');
        $this->addSql('ALTER TABLE classe DROP FOREIGN KEY FK_9621439DD823E37A');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY evaluation_ibfk_3');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY evaluation_ibfk_2');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY evaluation_ibfk_1');
        $this->addSql('ALTER TABLE modalities_subscriptions DROP FOREIGN KEY FK_6582079CCC33534F');
        $this->addSql('ALTER TABLE modalities_subscriptions DROP FOREIGN KEY FK_6582079CCB944F1A');
        $this->addSql('ALTER TABLE modalities_subscriptions DROP FOREIGN KEY FK_6582079C9DC4B963');
        $this->addSql('ALTER TABLE modalities_subscriptions DROP FOREIGN KEY FK_6582079C14463F54');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840DF675F31B');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D9C6BD325');
        $this->addSql('ALTER TABLE report_card_template DROP FOREIGN KEY report_card_template_ibfk_1');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABBB069795C');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY school_ibfk_2');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY school_ibfk_1');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA223CC33534F');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA223CB944F1A');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA223C32A47EE');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA2239DC4B963');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA22314463F54');
        $this->addSql('ALTER TABLE school_class_attendance DROP FOREIGN KEY FK_410B528456C5646');
        $this->addSql('ALTER TABLE school_class_attendance DROP FOREIGN KEY FK_410B52814463F54');
        $this->addSql('ALTER TABLE school_class_grade DROP FOREIGN KEY FK_EC8BBDB2456C5646');
        $this->addSql('ALTER TABLE school_class_grade DROP FOREIGN KEY FK_EC8BBDB223EDC87');
        $this->addSql('ALTER TABLE school_class_grade DROP FOREIGN KEY FK_EC8BBDB214463F54');
        $this->addSql('ALTER TABLE school_class_numbering_type DROP FOREIGN KEY school_class_numbering_type_ibfk_2');
        $this->addSql('ALTER TABLE school_class_numbering_type DROP FOREIGN KEY school_class_numbering_type_ibfk_1');
        $this->addSql('ALTER TABLE school_class_payment_modals DROP FOREIGN KEY FK_662FC679C32A47EE');
        $this->addSql('ALTER TABLE school_class_payment_modals DROP FOREIGN KEY FK_662FC6799DC4B963');
        $this->addSql('ALTER TABLE school_class_payment_modals DROP FOREIGN KEY FK_662FC67914463F54');
        $this->addSql('ALTER TABLE school_class_period DROP FOREIGN KEY school_class_period_ibfk_3');
        $this->addSql('ALTER TABLE school_class_period DROP FOREIGN KEY school_class_period_ibfk_2');
        $this->addSql('ALTER TABLE school_class_period DROP FOREIGN KEY school_class_period_ibfk_1');
        $this->addSql('ALTER TABLE school_class_period DROP FOREIGN KEY FK_33B1AF85EC8B7ADE');
        $this->addSql('ALTER TABLE school_class_period DROP FOREIGN KEY FK_33B1AF85C32A47EE');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY school_class_subject_ibfk_1');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY school_class_subject_ibfk_5');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY school_class_subject_ibfk_3');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY school_class_subject_ibfk_2');
        $this->addSql('ALTER TABLE school_class_subject_group DROP FOREIGN KEY FK_BE74C7FDFB00225A');
        $this->addSql('ALTER TABLE school_class_subject_group DROP FOREIGN KEY FK_BE74C7FDC32A47EE');
        $this->addSql('ALTER TABLE school_class_subject_group DROP FOREIGN KEY FK_BE74C7FD14463F54');
        $this->addSql('ALTER TABLE school_evaluation DROP FOREIGN KEY FK_A6822587EC8B7ADE');
        $this->addSql('ALTER TABLE school_evaluation DROP FOREIGN KEY FK_A68225875EEADD3B');
        $this->addSql('ALTER TABLE school_evaluation DROP FOREIGN KEY FK_A68225873FA3C347');
        $this->addSql('ALTER TABLE school_evaluation_time DROP FOREIGN KEY school_evaluation_time_ibfk_2');
        $this->addSql('ALTER TABLE school_evaluation_time DROP FOREIGN KEY school_evaluation_time_ibfk_1');
        $this->addSql('ALTER TABLE school_license_payment DROP FOREIGN KEY school_license_payment_ibfk_1');
        $this->addSql('ALTER TABLE school_section DROP FOREIGN KEY FK_BF5C4877D823E37A');
        $this->addSql('ALTER TABLE school_section DROP FOREIGN KEY FK_BF5C4877C32A47EE');
        $this->addSql('ALTER TABLE school_study_type DROP FOREIGN KEY school_study_type_ibfk_2');
        $this->addSql('ALTER TABLE school_study_type DROP FOREIGN KEY school_study_type_ibfk_1');
        $this->addSql('ALTER TABLE section_category_subject DROP FOREIGN KEY FK_DC5615E0FB00225A');
        $this->addSql('ALTER TABLE section_category_subject DROP FOREIGN KEY FK_DC5615E04B7E29D');
        $this->addSql('ALTER TABLE section_category_subject_group DROP FOREIGN KEY FK_334937034B7E29D');
        $this->addSql('ALTER TABLE student_attendance DROP FOREIGN KEY FK_803CE07014463F54');
        $this->addSql('ALTER TABLE student_attendance DROP FOREIGN KEY FK_803CE070CB944F1A');
        $this->addSql('ALTER TABLE student_class DROP FOREIGN KEY FK_657C6002CB944F1A');
        $this->addSql('ALTER TABLE student_class DROP FOREIGN KEY FK_657C600214463F54');
        $this->addSql('ALTER TABLE student_class_attendance DROP FOREIGN KEY student_class_attendance_ibfk_2');
        $this->addSql('ALTER TABLE student_class_attendance DROP FOREIGN KEY student_class_attendance_ibfk_1');
        $this->addSql('ALTER TABLE student_class_timetable_presence DROP FOREIGN KEY student_class_timetable_presence_ibfk_3');
        $this->addSql('ALTER TABLE student_class_timetable_presence DROP FOREIGN KEY student_class_timetable_presence_ibfk_2');
        $this->addSql('ALTER TABLE student_class_timetable_presence DROP FOREIGN KEY student_class_timetable_presence_ibfk_1');
        $this->addSql('ALTER TABLE student_note DROP FOREIGN KEY FK_F09E81CCCB944F1A');
        $this->addSql('ALTER TABLE student_note DROP FOREIGN KEY FK_F09E81CC14463F54');
        $this->addSql('ALTER TABLE subject_grade DROP FOREIGN KEY FK_48C96FECDC3D0C33');
        $this->addSql('ALTER TABLE subject_grade DROP FOREIGN KEY FK_48C96FEC456C5646');
        $this->addSql('ALTER TABLE subject_grade DROP FOREIGN KEY FK_48C96FEC23EDC87');
        $this->addSql('ALTER TABLE subject_grade DROP FOREIGN KEY FK_48C96FECEC8B7ADE');
        $this->addSql('ALTER TABLE subject_group DROP FOREIGN KEY subject_group_ibfk_3');
        $this->addSql('ALTER TABLE subject_group DROP FOREIGN KEY subject_group_ibfk_2');
        $this->addSql('ALTER TABLE teacher_class DROP FOREIGN KEY FK_BCB4A5C2EC8B7ADE');
        $this->addSql('ALTER TABLE teacher_class DROP FOREIGN KEY FK_BCB4A5C241807E1D');
        $this->addSql('ALTER TABLE teacher_class DROP FOREIGN KEY FK_BCB4A5C214463F54');
        $this->addSql('ALTER TABLE timetable DROP FOREIGN KEY timetable_ibfk_3');
        $this->addSql('ALTER TABLE timetable DROP FOREIGN KEY timetable_ibfk_2');
        $this->addSql('ALTER TABLE timetable DROP FOREIGN KEY timetable_ibfk_1');
        $this->addSql('ALTER TABLE timetable_day DROP FOREIGN KEY timetable_day_ibfk_1');
        $this->addSql('ALTER TABLE timetable_slot DROP FOREIGN KEY timetable_slot_ibfk_3');
        $this->addSql('ALTER TABLE timetable_slot DROP FOREIGN KEY timetable_slot_ibfk_2');
        $this->addSql('ALTER TABLE timetable_slot DROP FOREIGN KEY timetable_slot_ibfk_1');
        $this->addSql('DROP TABLE admission_reductions');
        $this->addSql('DROP TABLE app_license');
        $this->addSql('DROP TABLE class_occurence');
        $this->addSql('DROP TABLE class_subject_module');
        $this->addSql('DROP TABLE classe');
        $this->addSql('DROP TABLE core_update');
        $this->addSql('DROP TABLE evaluation');
        $this->addSql('DROP TABLE evaluation_appreciation_bareme');
        $this->addSql('DROP TABLE evaluation_appreciation_template');
        $this->addSql('DROP TABLE fees');
        $this->addSql('DROP TABLE modalities_subscriptions');
        $this->addSql('DROP TABLE module');
        $this->addSql('DROP TABLE operation_logs');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE registration_card_base_config');
        $this->addSql('DROP TABLE report_card_template');
        $this->addSql('DROP TABLE school');
        $this->addSql('DROP TABLE school_class_admission_payments');
        $this->addSql('DROP TABLE school_class_attendance');
        $this->addSql('DROP TABLE school_class_grade');
        $this->addSql('DROP TABLE school_class_numbering_type');
        $this->addSql('DROP TABLE school_class_payment_modals');
        $this->addSql('DROP TABLE school_class_period');
        $this->addSql('DROP TABLE school_class_subject');
        $this->addSql('DROP TABLE school_class_subject_group');
        $this->addSql('DROP TABLE school_evaluation');
        $this->addSql('DROP TABLE school_evaluation_frame');
        $this->addSql('DROP TABLE school_evaluation_time');
        $this->addSql('DROP TABLE school_evaluation_time_type');
        $this->addSql('DROP TABLE school_license_payment');
        $this->addSql('DROP TABLE school_period');
        $this->addSql('DROP TABLE school_section');
        $this->addSql('DROP TABLE school_study_type');
        $this->addSql('DROP TABLE section_category_subject');
        $this->addSql('DROP TABLE section_category_subject_group');
        $this->addSql('DROP TABLE student_attendance');
        $this->addSql('DROP TABLE student_class');
        $this->addSql('DROP TABLE student_class_attendance');
        $this->addSql('DROP TABLE student_class_timetable_presence');
        $this->addSql('DROP TABLE student_note');
        $this->addSql('DROP TABLE studies_type');
        $this->addSql('DROP TABLE study_level');
        $this->addSql('DROP TABLE study_subject');
        $this->addSql('DROP TABLE subject_grade');
        $this->addSql('DROP TABLE subject_group');
        $this->addSql('DROP TABLE subjects_modules');
        $this->addSql('DROP TABLE teacher_class');
        $this->addSql('DROP TABLE timetable');
        $this->addSql('DROP TABLE timetable_day');
        $this->addSql('DROP TABLE timetable_slot');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649208F64F1');
        $this->addSql('ALTER TABLE user CHANGE reset_password reset_password TINYINT(1) NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649208F64F1 FOREIGN KEY (tutor_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE user RENAME INDEX national_registration_number TO UNIQ_8D93D64971D0A9E8');
        $this->addSql('CREATE UNIQUE INDEX unique_user_school ON user_base_configuration (user_id, school_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admission_reductions (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, school_class_period_id INT NOT NULL, school_period_id INT NOT NULL, student_id INT NOT NULL, reduction_modal_id INT NOT NULL, requested_by_id INT DEFAULT NULL, approved_by_id INT DEFAULT NULL, reduction_amount BIGINT NOT NULL, date_created DATETIME NOT NULL, date_updated DATETIME NOT NULL, pending_approval TINYINT(1) DEFAULT 1 NOT NULL, approval_owners VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, approved TINYINT(1) DEFAULT 0 NOT NULL, UNIQUE INDEX reduction_modal_id (reduction_modal_id, school_class_period_id, student_id), INDEX IDX_BA9FE4EBC32A47EE (school_id), INDEX IDX_BA9FE4EB14463F54 (school_class_period_id), INDEX IDX_BA9FE4EB9DC4B963 (school_period_id), INDEX IDX_BA9FE4EBCB944F1A (student_id), INDEX IDX_BA9FE4EB8373D28E (reduction_modal_id), INDEX approved_by_id (approved_by_id), INDEX requested_by_id (requested_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE app_license (id INT AUTO_INCREMENT NOT NULL, school_id INT DEFAULT NULL, licence_start_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, licence_duration INT DEFAULT 30 NOT NULL, licence_amount BIGINT DEFAULT 100000 NOT NULL, license_hash VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, enabled TINYINT(1) DEFAULT 0 NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, license_type VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'trial\' NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX school_id (school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE class_occurence (id INT AUTO_INCREMENT NOT NULL, classe_id INT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, slug VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX name (name), INDEX classe_id (classe_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE class_subject_module (id BIGINT AUTO_INCREMENT NOT NULL, subject_id INT NOT NULL, class_id INT NOT NULL, period_id INT NOT NULL, school_id INT NOT NULL, module_id INT NOT NULL, module_notation DOUBLE PRECISION NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX module_id (module_id, subject_id, class_id, period_id, school_id), INDEX class_subject_module_ibfk_1 (class_id), INDEX class_subject_module_ibfk_2 (period_id), INDEX class_subject_module_ibfk_3 (school_id), INDEX class_subject_module_ibfk_4 (subject_id), INDEX IDX_42B3F1CBAFC2B591 (module_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE classe (id INT AUTO_INCREMENT NOT NULL, study_level_id INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, slug VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX name (name, study_level_id), INDEX IDX_9621439DD823E37A (study_level_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE core_update (id INT AUTO_INCREMENT NOT NULL, version VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE evaluation (id BIGINT AUTO_INCREMENT NOT NULL, student_id INT NOT NULL, class_subject_module_id BIGINT NOT NULL, time_id INT NOT NULL, evaluation_note DOUBLE PRECISION NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX student_id (student_id), INDEX time_id (time_id), INDEX evaluation_ibfk_2 (class_subject_module_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE evaluation_appreciation_bareme (id INT AUTO_INCREMENT NOT NULL, evaluation_appreciation_template_id INT NOT NULL, evaluation_appreciation_max_note BIGINT NOT NULL, evaluation_appreciation_value VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, evaluation_appreciation_full_value VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX evaluation_appreciation_value (evaluation_appreciation_value, evaluation_appreciation_template_id), UNIQUE INDEX evaluation_appreciation_max_note (evaluation_appreciation_max_note, evaluation_appreciation_value, evaluation_appreciation_template_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE evaluation_appreciation_template (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, enabled TINYINT(1) DEFAULT 0 NOT NULL, UNIQUE INDEX name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE fees (id INT AUTO_INCREMENT NOT NULL, amount DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE modalities_subscriptions (id INT AUTO_INCREMENT NOT NULL, student_id INT NOT NULL, school_class_period_id INT NOT NULL, school_period_id INT NOT NULL, payment_modal_id INT NOT NULL, subscription_date DATETIME NOT NULL, enabled TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, is_full TINYINT(1) DEFAULT 0 NOT NULL, is_full_period VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_6582079CCB944F1A (student_id), INDEX IDX_6582079C14463F54 (school_class_period_id), INDEX IDX_6582079C9DC4B963 (school_period_id), INDEX IDX_6582079CCC33534F (payment_modal_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE module (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, enabled TINYINT(1) DEFAULT 0 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE operation_logs (id INT AUTO_INCREMENT NOT NULL, operation_type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, entity_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, entity_id INT DEFAULT NULL, status VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, error_message LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, timestamp DATETIME NOT NULL, performed_by VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, additional_data LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE payment (id INT AUTO_INCREMENT NOT NULL, author_id INT DEFAULT NULL, fees_id INT DEFAULT NULL, amount DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL, for_month DATE NOT NULL, INDEX IDX_6D28840DF675F31B (author_id), INDEX IDX_6D28840D9C6BD325 (fees_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE registration_card_base_config (id INT AUTO_INCREMENT NOT NULL, card_header VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, national_motto VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, head_officer_sign VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, card_bg VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, sign_title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, card_header_a VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, national_motto_a VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, double_header_layout TINYINT(1) DEFAULT 0 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE report_card_template (id INT AUTO_INCREMENT NOT NULL, evaluation_appreciation_template_id INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, header_left TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, header_right TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, national_motto_left VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, national_motto_right VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, header_title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, additional_header_left TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, additional_header_right TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, school_values_left TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, school_values_right TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX name (name), INDEX id_evaluation_appreciation_template_id (evaluation_appreciation_template_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school (id INT AUTO_INCREMENT NOT NULL, registration_base_config_id INT DEFAULT NULL, evaluation_appreciation_template_id INT DEFAULT NULL, report_card_template_id INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, address LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, contact_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, contact_phone VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, contact_email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, trial_start_at DATE DEFAULT NULL, trial_duration INT DEFAULT NULL, created_at DATETIME NOT NULL, customer TINYINT(1) NOT NULL, acronym VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, school_number VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, license_hash VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, last_acces_at DATETIME DEFAULT NULL, admin_only TINYINT(1) DEFAULT 0 NOT NULL, school_values TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX UNIQ_F99EDABB6B2C1C98 (school_number), UNIQUE INDEX UNIQ_F99EDABBB069795C (registration_base_config_id), INDEX evaluation_appreciation_template_id (evaluation_appreciation_template_id), INDEX report_card_template_id (report_card_template_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_class_admission_payments (id INT AUTO_INCREMENT NOT NULL, school_class_period_id INT NOT NULL, student_id INT NOT NULL, school_id INT NOT NULL, school_period_id INT NOT NULL, payment_modal_id INT NOT NULL, payment_date DATETIME NOT NULL, payment_amount BIGINT DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, modal_type VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_33FDA22314463F54 (school_class_period_id), INDEX IDX_33FDA223CB944F1A (student_id), INDEX IDX_33FDA223C32A47EE (school_id), INDEX IDX_33FDA2239DC4B963 (school_period_id), INDEX IDX_33FDA223CC33534F (payment_modal_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_class_attendance (id INT AUTO_INCREMENT NOT NULL, evaluation_id INT DEFAULT NULL, school_class_id INT DEFAULT NULL, attendanc_json JSON NOT NULL, INDEX IDX_410B528456C5646 (evaluation_id), INDEX IDX_410B52814463F54 (school_class_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_class_grade (id INT AUTO_INCREMENT NOT NULL, subject_id INT DEFAULT NULL, evaluation_id INT DEFAULT NULL, school_class_id INT DEFAULT NULL, notes_json JSON NOT NULL, created_at DATETIME NOT NULL, enabled TINYINT(1) NOT NULL, INDEX IDX_EC8BBDB223EDC87 (subject_id), INDEX IDX_EC8BBDB2456C5646 (evaluation_id), INDEX IDX_EC8BBDB214463F54 (school_class_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_class_numbering_type (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, classe_id INT NOT NULL, numbering_type VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX school_id (school_id), INDEX section_category_id (classe_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_class_payment_modals (id INT AUTO_INCREMENT NOT NULL, school_class_period_id INT DEFAULT NULL, school_period_id INT NOT NULL, school_id INT NOT NULL, label VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, amount BIGINT NOT NULL, due_date DATE NOT NULL, modal_type VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, modal_priority INT DEFAULT 0 NOT NULL, UNIQUE INDEX unique_class_school_period (school_class_period_id, school_id, school_period_id, label, modal_priority), INDEX IDX_662FC67914463F54 (school_class_period_id), INDEX IDX_662FC6799DC4B963 (school_period_id), INDEX IDX_662FC679C32A47EE (school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_class_period (id INT AUTO_INCREMENT NOT NULL, school_id INT DEFAULT NULL, period_id INT DEFAULT NULL, evaluation_appreciation_template_id INT DEFAULT NULL, class_master_id INT DEFAULT NULL, class_occurence_id INT NOT NULL, report_card_template_id INT DEFAULT NULL, UNIQUE INDEX school_id_period_id_class_occurence_id (school_id, period_id, class_occurence_id), INDEX IDX_33B1AF85C32A47EE (school_id), INDEX IDX_33B1AF85EC8B7ADE (period_id), INDEX evaluation_appreciation_template_id (evaluation_appreciation_template_id), INDEX class_master_id (class_master_id), INDEX class_occurence_id (class_occurence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_class_subject (id INT AUTO_INCREMENT NOT NULL, school_class_period_id INT NOT NULL, study_subject_id INT NOT NULL, group_id INT DEFAULT NULL, teacher_id INT DEFAULT NULL, coefficient INT NOT NULL, awaited_skills TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX study_subject_id (study_subject_id, school_class_period_id), INDEX school_class_id (school_class_period_id), INDEX group_id (group_id), INDEX teacher_id (teacher_id), INDEX IDX_12A9F5B885A2B8E7 (study_subject_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_class_subject_group (id INT AUTO_INCREMENT NOT NULL, school_class_id INT DEFAULT NULL, school_id INT DEFAULT NULL, section_category_subject_group_id INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, position INT NOT NULL, INDEX IDX_BE74C7FD14463F54 (school_class_id), INDEX IDX_BE74C7FDC32A47EE (school_id), INDEX IDX_BE74C7FDFB00225A (section_category_subject_group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_evaluation (id INT AUTO_INCREMENT NOT NULL, frame_id INT DEFAULT NULL, time_id INT DEFAULT NULL, period_id INT DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_A68225873FA3C347 (frame_id), INDEX IDX_A68225875EEADD3B (time_id), INDEX IDX_A6822587EC8B7ADE (period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_evaluation_frame (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, slug VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, short_name VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_evaluation_time (id INT AUTO_INCREMENT NOT NULL, evaluation_frame_id INT DEFAULT NULL, type_id INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, slug VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, short_name VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX evaluation_frame_id (evaluation_frame_id), INDEX type_id (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_evaluation_time_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_license_payment (id INT AUTO_INCREMENT NOT NULL, license_id INT NOT NULL, date_payment DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, payment_amount BIGINT NOT NULL, payment_method VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX license_id (license_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_period (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, enabled TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_section (id INT AUTO_INCREMENT NOT NULL, school_id INT DEFAULT NULL, study_level_id INT DEFAULT NULL, INDEX IDX_BF5C4877C32A47EE (school_id), INDEX IDX_BF5C4877D823E37A (study_level_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE school_study_type (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, studies_type_id INT NOT NULL, UNIQUE INDEX school_id (school_id, studies_type_id), INDEX studies_type_id (studies_type_id), INDEX IDX_46A73FE2C32A47EE (school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE section_category_subject (id INT AUTO_INCREMENT NOT NULL, section_category_id INT DEFAULT NULL, section_category_subject_group_id INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, slug VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_DC5615E04B7E29D (section_category_id), INDEX IDX_DC5615E0FB00225A (section_category_subject_group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE section_category_subject_group (id INT AUTO_INCREMENT NOT NULL, section_category_id INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, code VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_334937034B7E29D (section_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE student_attendance (id INT AUTO_INCREMENT NOT NULL, student_id INT DEFAULT NULL, school_class_id INT DEFAULT NULL, abscence INT NOT NULL, INDEX IDX_803CE070CB944F1A (student_id), INDEX IDX_803CE07014463F54 (school_class_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE student_class (id INT AUTO_INCREMENT NOT NULL, student_id INT DEFAULT NULL, school_class_period_id INT DEFAULT NULL, UNIQUE INDEX school_class_period_id (school_class_period_id, student_id), INDEX IDX_657C6002CB944F1A (student_id), INDEX IDX_657C600214463F54 (school_class_period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE student_class_attendance (id INT AUTO_INCREMENT NOT NULL, student_class_id INT NOT NULL, time_id INT NOT NULL, heures_absence INT DEFAULT 0 NOT NULL, absences_justifiee INT DEFAULT 0 NOT NULL, retard INT DEFAULT 0 NOT NULL, retard_injustifie INT DEFAULT 0 NOT NULL, retenue INT DEFAULT 0 NOT NULL, avertissement_discipline INT DEFAULT 0 NOT NULL, blame INT DEFAULT 0 NOT NULL, jour_exclusion INT DEFAULT 0 NOT NULL, exclusion_definitive TINYINT(1) DEFAULT 0 NOT NULL, UNIQUE INDEX time_id (time_id, student_class_id), INDEX student_class_id (student_class_id), INDEX IDX_9BFDE465EEADD3B (time_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE student_class_timetable_presence (id INT AUTO_INCREMENT NOT NULL, student_class_id INT NOT NULL, time_table_slot_id INT NOT NULL, school_evaluation_time_id INT NOT NULL, status TINYINT(1) DEFAULT 0 NOT NULL, date_presence DATE NOT NULL, locked TINYINT(1) DEFAULT 0 NOT NULL, INDEX student_class_id (student_class_id), INDEX time_table_slot_id (time_table_slot_id), INDEX school_evaluation_time_id (school_evaluation_time_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE student_note (id INT AUTO_INCREMENT NOT NULL, student_id INT DEFAULT NULL, school_class_id INT DEFAULT NULL, note INT DEFAULT NULL, INDEX IDX_F09E81CCCB944F1A (student_id), INDEX IDX_F09E81CC14463F54 (school_class_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE studies_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE study_level (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, slug VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE study_subject (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, slug VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE subject_grade (id INT AUTO_INCREMENT NOT NULL, evaluation_id INT DEFAULT NULL, subject_id INT DEFAULT NULL, s_class_id INT DEFAULT NULL, period_id INT DEFAULT NULL, created_at DATETIME NOT NULL, student_ids_and_grades JSON NOT NULL, uploaded_at DATETIME DEFAULT NULL, INDEX IDX_48C96FEC456C5646 (evaluation_id), INDEX IDX_48C96FEC23EDC87 (subject_id), INDEX IDX_48C96FECDC3D0C33 (s_class_id), INDEX IDX_48C96FECEC8B7ADE (period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE subject_group (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, period_id INT NOT NULL, pos_order INT NOT NULL, description VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX description (description), INDEX period_id (period_id), INDEX school_id (school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE subjects_modules (id INT AUTO_INCREMENT NOT NULL, module_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, module_slug VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX module_name (module_name), UNIQUE INDEX module_slug (module_slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE teacher_class (id INT AUTO_INCREMENT NOT NULL, teacher_id INT DEFAULT NULL, school_class_id INT DEFAULT NULL, period_id INT DEFAULT NULL, INDEX IDX_BCB4A5C241807E1D (teacher_id), INDEX IDX_BCB4A5C214463F54 (school_class_id), INDEX IDX_BCB4A5C2EC8B7ADE (period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE timetable (id INT AUTO_INCREMENT NOT NULL, teacher_id INT NOT NULL, school_id INT NOT NULL, period_id INT NOT NULL, label VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX timetable_ibfk_1 (period_id), INDEX timetable_ibfk_2 (school_id), INDEX tacher_id (teacher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE timetable_day (id INT AUTO_INCREMENT NOT NULL, timetable_id INT NOT NULL, day_of_week INT NOT NULL, UNIQUE INDEX day_of_week (day_of_week, timetable_id), INDEX timetable_id (timetable_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE timetable_slot (id INT AUTO_INCREMENT NOT NULL, timetable_day_id INT NOT NULL, subject_id INT NOT NULL, school_class_period_id INT NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL, notes TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX school_class_id (school_class_period_id, subject_id, timetable_day_id), UNIQUE INDEX end_time_2 (end_time, school_class_period_id, start_time, subject_id, timetable_day_id), UNIQUE INDEX end_time_3 (end_time, start_time, timetable_day_id, school_class_period_id), INDEX subject_id (subject_id), INDEX timetable_day_id (timetable_day_id), INDEX IDX_3932CA6919F13D4D (school_class_period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EBCB944F1A FOREIGN KEY (student_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EBC32A47EE FOREIGN KEY (school_id) REFERENCES school (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EB9DC4B963 FOREIGN KEY (school_period_id) REFERENCES school_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT admission_reductions_ibfk_3 FOREIGN KEY (requested_by_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EB8373D28E FOREIGN KEY (reduction_modal_id) REFERENCES school_class_payment_modals (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EB14463F54 FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT admission_reductions_ibfk_2 FOREIGN KEY (approved_by_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE app_license ADD CONSTRAINT app_license_ibfk_1 FOREIGN KEY (school_id) REFERENCES school (id) ON UPDATE SET NULL ON DELETE CASCADE');
        $this->addSql('ALTER TABLE class_occurence ADD CONSTRAINT class_occurence_ibfk_1 FOREIGN KEY (classe_id) REFERENCES classe (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT class_subject_module_ibfk_6 FOREIGN KEY (subject_id) REFERENCES study_subject (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT class_subject_module_ibfk_5 FOREIGN KEY (module_id) REFERENCES subjects_modules (id) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT class_subject_module_ibfk_3 FOREIGN KEY (school_id) REFERENCES school (id) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT class_subject_module_ibfk_2 FOREIGN KEY (period_id) REFERENCES school_period (id) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT class_subject_module_ibfk_1 FOREIGN KEY (class_id) REFERENCES school_class_period (id) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE classe ADD CONSTRAINT FK_9621439DD823E37A FOREIGN KEY (study_level_id) REFERENCES study_level (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT evaluation_ibfk_3 FOREIGN KEY (time_id) REFERENCES school_evaluation_time (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT evaluation_ibfk_2 FOREIGN KEY (class_subject_module_id) REFERENCES class_subject_module (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT evaluation_ibfk_1 FOREIGN KEY (student_id) REFERENCES student_class (id)');
        $this->addSql('ALTER TABLE modalities_subscriptions ADD CONSTRAINT FK_6582079CCC33534F FOREIGN KEY (payment_modal_id) REFERENCES school_class_payment_modals (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE modalities_subscriptions ADD CONSTRAINT FK_6582079CCB944F1A FOREIGN KEY (student_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE modalities_subscriptions ADD CONSTRAINT FK_6582079C9DC4B963 FOREIGN KEY (school_period_id) REFERENCES school_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE modalities_subscriptions ADD CONSTRAINT FK_6582079C14463F54 FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DF675F31B FOREIGN KEY (author_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D9C6BD325 FOREIGN KEY (fees_id) REFERENCES fees (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE report_card_template ADD CONSTRAINT report_card_template_ibfk_1 FOREIGN KEY (evaluation_appreciation_template_id) REFERENCES evaluation_appreciation_template (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABBB069795C FOREIGN KEY (registration_base_config_id) REFERENCES registration_card_base_config (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT school_ibfk_2 FOREIGN KEY (report_card_template_id) REFERENCES report_card_template (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT school_ibfk_1 FOREIGN KEY (evaluation_appreciation_template_id) REFERENCES evaluation_appreciation_template (id)');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA223CC33534F FOREIGN KEY (payment_modal_id) REFERENCES school_class_payment_modals (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA223CB944F1A FOREIGN KEY (student_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA223C32A47EE FOREIGN KEY (school_id) REFERENCES school (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA2239DC4B963 FOREIGN KEY (school_period_id) REFERENCES school_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA22314463F54 FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_attendance ADD CONSTRAINT FK_410B528456C5646 FOREIGN KEY (evaluation_id) REFERENCES school_evaluation (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_attendance ADD CONSTRAINT FK_410B52814463F54 FOREIGN KEY (school_class_id) REFERENCES school_class_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_grade ADD CONSTRAINT FK_EC8BBDB2456C5646 FOREIGN KEY (evaluation_id) REFERENCES school_evaluation (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_grade ADD CONSTRAINT FK_EC8BBDB223EDC87 FOREIGN KEY (subject_id) REFERENCES study_subject (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_grade ADD CONSTRAINT FK_EC8BBDB214463F54 FOREIGN KEY (school_class_id) REFERENCES school_class_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_numbering_type ADD CONSTRAINT school_class_numbering_type_ibfk_2 FOREIGN KEY (classe_id) REFERENCES classe (id)');
        $this->addSql('ALTER TABLE school_class_numbering_type ADD CONSTRAINT school_class_numbering_type_ibfk_1 FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_class_payment_modals ADD CONSTRAINT FK_662FC679C32A47EE FOREIGN KEY (school_id) REFERENCES school (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_payment_modals ADD CONSTRAINT FK_662FC6799DC4B963 FOREIGN KEY (school_period_id) REFERENCES school_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_payment_modals ADD CONSTRAINT FK_662FC67914463F54 FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_period ADD CONSTRAINT school_class_period_ibfk_3 FOREIGN KEY (class_occurence_id) REFERENCES class_occurence (id)');
        $this->addSql('ALTER TABLE school_class_period ADD CONSTRAINT school_class_period_ibfk_2 FOREIGN KEY (class_master_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE school_class_period ADD CONSTRAINT school_class_period_ibfk_1 FOREIGN KEY (evaluation_appreciation_template_id) REFERENCES evaluation_appreciation_template (id)');
        $this->addSql('ALTER TABLE school_class_period ADD CONSTRAINT FK_33B1AF85EC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_period ADD CONSTRAINT FK_33B1AF85C32A47EE FOREIGN KEY (school_id) REFERENCES school (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT school_class_subject_ibfk_1 FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT school_class_subject_ibfk_5 FOREIGN KEY (teacher_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT school_class_subject_ibfk_3 FOREIGN KEY (group_id) REFERENCES subject_group (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT school_class_subject_ibfk_2 FOREIGN KEY (study_subject_id) REFERENCES study_subject (id)');
        $this->addSql('ALTER TABLE school_class_subject_group ADD CONSTRAINT FK_BE74C7FDFB00225A FOREIGN KEY (section_category_subject_group_id) REFERENCES section_category_subject_group (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_subject_group ADD CONSTRAINT FK_BE74C7FDC32A47EE FOREIGN KEY (school_id) REFERENCES school (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_class_subject_group ADD CONSTRAINT FK_BE74C7FD14463F54 FOREIGN KEY (school_class_id) REFERENCES school_class_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_evaluation ADD CONSTRAINT FK_A6822587EC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_evaluation ADD CONSTRAINT FK_A68225875EEADD3B FOREIGN KEY (time_id) REFERENCES school_evaluation_time (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_evaluation ADD CONSTRAINT FK_A68225873FA3C347 FOREIGN KEY (frame_id) REFERENCES school_evaluation_frame (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_evaluation_time ADD CONSTRAINT school_evaluation_time_ibfk_2 FOREIGN KEY (type_id) REFERENCES school_evaluation_time_type (id)');
        $this->addSql('ALTER TABLE school_evaluation_time ADD CONSTRAINT school_evaluation_time_ibfk_1 FOREIGN KEY (evaluation_frame_id) REFERENCES school_evaluation_frame (id)');
        $this->addSql('ALTER TABLE school_license_payment ADD CONSTRAINT school_license_payment_ibfk_1 FOREIGN KEY (license_id) REFERENCES app_license (id)');
        $this->addSql('ALTER TABLE school_section ADD CONSTRAINT FK_BF5C4877D823E37A FOREIGN KEY (study_level_id) REFERENCES study_level (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_section ADD CONSTRAINT FK_BF5C4877C32A47EE FOREIGN KEY (school_id) REFERENCES school (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE school_study_type ADD CONSTRAINT school_study_type_ibfk_2 FOREIGN KEY (studies_type_id) REFERENCES studies_type (id)');
        $this->addSql('ALTER TABLE school_study_type ADD CONSTRAINT school_study_type_ibfk_1 FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE section_category_subject ADD CONSTRAINT FK_DC5615E0FB00225A FOREIGN KEY (section_category_subject_group_id) REFERENCES section_category_subject_group (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE section_category_subject ADD CONSTRAINT FK_DC5615E04B7E29D FOREIGN KEY (section_category_id) REFERENCES classe (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE section_category_subject_group ADD CONSTRAINT FK_334937034B7E29D FOREIGN KEY (section_category_id) REFERENCES classe (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE student_attendance ADD CONSTRAINT FK_803CE07014463F54 FOREIGN KEY (school_class_id) REFERENCES school_class_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE student_attendance ADD CONSTRAINT FK_803CE070CB944F1A FOREIGN KEY (student_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE student_class ADD CONSTRAINT FK_657C6002CB944F1A FOREIGN KEY (student_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE student_class ADD CONSTRAINT FK_657C600214463F54 FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE student_class_attendance ADD CONSTRAINT student_class_attendance_ibfk_2 FOREIGN KEY (student_class_id) REFERENCES student_class (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE student_class_attendance ADD CONSTRAINT student_class_attendance_ibfk_1 FOREIGN KEY (time_id) REFERENCES school_evaluation_time (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE student_class_timetable_presence ADD CONSTRAINT student_class_timetable_presence_ibfk_3 FOREIGN KEY (school_evaluation_time_id) REFERENCES school_evaluation_time (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE student_class_timetable_presence ADD CONSTRAINT student_class_timetable_presence_ibfk_2 FOREIGN KEY (time_table_slot_id) REFERENCES timetable_slot (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE student_class_timetable_presence ADD CONSTRAINT student_class_timetable_presence_ibfk_1 FOREIGN KEY (student_class_id) REFERENCES student_class (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE student_note ADD CONSTRAINT FK_F09E81CCCB944F1A FOREIGN KEY (student_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE student_note ADD CONSTRAINT FK_F09E81CC14463F54 FOREIGN KEY (school_class_id) REFERENCES school_class_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE subject_grade ADD CONSTRAINT FK_48C96FECDC3D0C33 FOREIGN KEY (s_class_id) REFERENCES school_class_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE subject_grade ADD CONSTRAINT FK_48C96FEC456C5646 FOREIGN KEY (evaluation_id) REFERENCES school_evaluation (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE subject_grade ADD CONSTRAINT FK_48C96FEC23EDC87 FOREIGN KEY (subject_id) REFERENCES section_category_subject (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE subject_grade ADD CONSTRAINT FK_48C96FECEC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE subject_group ADD CONSTRAINT subject_group_ibfk_3 FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE subject_group ADD CONSTRAINT subject_group_ibfk_2 FOREIGN KEY (period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE teacher_class ADD CONSTRAINT FK_BCB4A5C2EC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE teacher_class ADD CONSTRAINT FK_BCB4A5C241807E1D FOREIGN KEY (teacher_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE teacher_class ADD CONSTRAINT FK_BCB4A5C214463F54 FOREIGN KEY (school_class_id) REFERENCES school_class_period (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE timetable ADD CONSTRAINT timetable_ibfk_3 FOREIGN KEY (teacher_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable ADD CONSTRAINT timetable_ibfk_2 FOREIGN KEY (school_id) REFERENCES school (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable ADD CONSTRAINT timetable_ibfk_1 FOREIGN KEY (period_id) REFERENCES school_period (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable_day ADD CONSTRAINT timetable_day_ibfk_1 FOREIGN KEY (timetable_id) REFERENCES timetable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable_slot ADD CONSTRAINT timetable_slot_ibfk_3 FOREIGN KEY (timetable_day_id) REFERENCES timetable_day (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable_slot ADD CONSTRAINT timetable_slot_ibfk_2 FOREIGN KEY (subject_id) REFERENCES study_subject (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable_slot ADD CONSTRAINT timetable_slot_ibfk_1 FOREIGN KEY (school_class_period_id) REFERENCES school_class_period (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D649208F64F1');
        $this->addSql('ALTER TABLE `user` CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE reset_password reset_password TINYINT(1) DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D649208F64F1 FOREIGN KEY (tutor_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `user` RENAME INDEX uniq_8d93d64971d0a9e8 TO national_registration_number');
        $this->addSql('DROP INDEX unique_user_school ON user_base_configuration');
    }
}
