<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250509085556 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admission_reductions (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, school_class_id INT NOT NULL, school_period_id INT NOT NULL, student_id INT NOT NULL, reduction_modal_id INT NOT NULL, reduction_amount BIGINT NOT NULL, date_created DATETIME NOT NULL, date_updated DATETIME NOT NULL, INDEX IDX_BA9FE4EBC32A47EE (school_id), INDEX IDX_BA9FE4EB14463F54 (school_class_id), INDEX IDX_BA9FE4EB9DC4B963 (school_period_id), INDEX IDX_BA9FE4EBCB944F1A (student_id), INDEX IDX_BA9FE4EB8373D28E (reduction_modal_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE class_subject_module (id INT AUTO_INCREMENT NOT NULL, subject_id INT NOT NULL, class_id INT NOT NULL, period_id INT NOT NULL, module_id INT NOT NULL, school_id INT NOT NULL, module_notation INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_42B3F1CB23EDC87 (subject_id), INDEX IDX_42B3F1CBEA000B10 (class_id), INDEX IDX_42B3F1CBEC8B7ADE (period_id), INDEX IDX_42B3F1CBAFC2B591 (module_id), INDEX IDX_42B3F1CBC32A47EE (school_id), UNIQUE INDEX UNIQ_42B3F1CB23EDC87EA000B10EC8B7ADEC32A47EE (subject_id, class_id, period_id, school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE core_update (id INT AUTO_INCREMENT NOT NULL, version VARCHAR(10) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE evaluation (id INT AUTO_INCREMENT NOT NULL, student_id INT NOT NULL, class_subject_module_id INT NOT NULL, time_id INT NOT NULL, evaluation_note DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_1323A575CB944F1A (student_id), INDEX IDX_1323A575A4748E19 (class_subject_module_id), INDEX IDX_1323A5755EEADD3B (time_id), UNIQUE INDEX UNIQ_1323A575CB944F1AA4748E195EEADD3B (student_id, class_subject_module_id, time_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fees (id INT AUTO_INCREMENT NOT NULL, amount DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE modalities_subscriptions (id INT AUTO_INCREMENT NOT NULL, student_id INT NOT NULL, school_class_id INT NOT NULL, school_period_id INT NOT NULL, payment_modal_id INT NOT NULL, subscription_date DATETIME NOT NULL, enabled TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, is_full TINYINT(1) DEFAULT 0 NOT NULL, is_full_period VARCHAR(20) DEFAULT NULL, INDEX IDX_6582079CCB944F1A (student_id), INDEX IDX_6582079C14463F54 (school_class_id), INDEX IDX_6582079C9DC4B963 (school_period_id), INDEX IDX_6582079CCC33534F (payment_modal_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operation_logs (id INT AUTO_INCREMENT NOT NULL, operation_type VARCHAR(255) NOT NULL, entity_name VARCHAR(255) DEFAULT NULL, entity_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, error_message LONGTEXT DEFAULT NULL, timestamp DATETIME NOT NULL, performed_by VARCHAR(255) NOT NULL, additional_data LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment (id INT AUTO_INCREMENT NOT NULL, author_id INT DEFAULT NULL, fees_id INT DEFAULT NULL, amount DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL, for_month DATE NOT NULL, INDEX IDX_6D28840DF675F31B (author_id), INDEX IDX_6D28840D9C6BD325 (fees_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE registration_card_base_config (id INT AUTO_INCREMENT NOT NULL, card_header VARCHAR(255) NOT NULL, national_motto VARCHAR(255) NOT NULL, head_officer_sign VARCHAR(255) NOT NULL, card_bg VARCHAR(255) NOT NULL, sign_title VARCHAR(255) DEFAULT NULL, card_header_a VARCHAR(255) DEFAULT NULL, national_motto_a VARCHAR(255) DEFAULT NULL, double_header_layout TINYINT(1) DEFAULT 0 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school (id INT AUTO_INCREMENT NOT NULL, fee_id INT DEFAULT NULL, registration_base_config_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, address LONGTEXT NOT NULL, contact_name VARCHAR(255) NOT NULL, contact_phone INT NOT NULL, contact_email VARCHAR(255) NOT NULL, logo VARCHAR(255) DEFAULT NULL, trial_start_at DATE DEFAULT NULL, trial_duration INT DEFAULT NULL, created_at DATETIME NOT NULL, customer TINYINT(1) NOT NULL, acronym VARCHAR(255) NOT NULL, school_number VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_F99EDABB6B2C1C98 (school_number), UNIQUE INDEX UNIQ_F99EDABBAB45AECA (fee_id), UNIQUE INDEX UNIQ_F99EDABBB069795C (registration_base_config_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_class (id INT AUTO_INCREMENT NOT NULL, school_id INT DEFAULT NULL, period_id INT DEFAULT NULL, section_category_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_33B1AF85C32A47EE (school_id), INDEX IDX_33B1AF85EC8B7ADE (period_id), INDEX IDX_33B1AF854B7E29D (section_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_class_admission_payments (id INT AUTO_INCREMENT NOT NULL, school_class_id INT NOT NULL, student_id INT NOT NULL, school_id INT NOT NULL, school_period_id INT NOT NULL, payment_modal_id INT NOT NULL, payment_date DATE NOT NULL, payment_amount BIGINT DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, modal_type VARCHAR(20) NOT NULL, INDEX IDX_33FDA22314463F54 (school_class_id), INDEX IDX_33FDA223CB944F1A (student_id), INDEX IDX_33FDA223C32A47EE (school_id), INDEX IDX_33FDA2239DC4B963 (school_period_id), INDEX IDX_33FDA223CC33534F (payment_modal_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_class_attendance (id INT AUTO_INCREMENT NOT NULL, evaluation_id INT DEFAULT NULL, school_class_id INT DEFAULT NULL, attendanc_json LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', INDEX IDX_410B528456C5646 (evaluation_id), INDEX IDX_410B52814463F54 (school_class_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_class_grade (id INT AUTO_INCREMENT NOT NULL, subject_id INT DEFAULT NULL, evaluation_id INT DEFAULT NULL, school_class_id INT DEFAULT NULL, notes_json LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME NOT NULL, enabled TINYINT(1) NOT NULL, INDEX IDX_EC8BBDB223EDC87 (subject_id), INDEX IDX_EC8BBDB2456C5646 (evaluation_id), INDEX IDX_EC8BBDB214463F54 (school_class_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_class_payment_modals (id INT AUTO_INCREMENT NOT NULL, school_class_id INT DEFAULT NULL, school_period_id INT NOT NULL, school_id INT NOT NULL, label VARCHAR(255) NOT NULL, amount BIGINT NOT NULL, due_date DATE NOT NULL, modal_type VARCHAR(20) NOT NULL, modal_priority INT DEFAULT 0 NOT NULL, INDEX IDX_662FC67914463F54 (school_class_id), INDEX IDX_662FC6799DC4B963 (school_period_id), INDEX IDX_662FC679C32A47EE (school_id), UNIQUE INDEX unique_class_school_period (school_class_id, school_id, school_period_id, label, modal_priority), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_class_subject (id INT AUTO_INCREMENT NOT NULL, school_id INT DEFAULT NULL, school_class_id INT DEFAULT NULL, period_id INT DEFAULT NULL, teacher_id INT DEFAULT NULL, section_category_subject_id INT DEFAULT NULL, school_class_subject_group_id INT DEFAULT NULL, group_id INT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, coefficient DOUBLE PRECISION NOT NULL, point_know_homw INT DEFAULT NULL, point_oral INT DEFAULT NULL, point_written INT DEFAULT NULL, point_practical INT DEFAULT NULL, target_skills LONGTEXT DEFAULT NULL, INDEX IDX_12A9F5B8C32A47EE (school_id), INDEX IDX_12A9F5B814463F54 (school_class_id), INDEX IDX_12A9F5B8EC8B7ADE (period_id), INDEX IDX_12A9F5B841807E1D (teacher_id), INDEX IDX_12A9F5B87A1E0799 (section_category_subject_id), INDEX IDX_12A9F5B888ED1A1 (school_class_subject_group_id), INDEX IDX_12A9F5B8FE54D947 (group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_class_subject_group (id INT AUTO_INCREMENT NOT NULL, school_class_id INT DEFAULT NULL, school_id INT DEFAULT NULL, section_category_subject_group_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, INDEX IDX_BE74C7FD14463F54 (school_class_id), INDEX IDX_BE74C7FDC32A47EE (school_id), INDEX IDX_BE74C7FDFB00225A (section_category_subject_group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_evaluation (id INT AUTO_INCREMENT NOT NULL, frame_id INT DEFAULT NULL, time_id INT DEFAULT NULL, period_id INT DEFAULT NULL, creted_at DATETIME NOT NULL, INDEX IDX_A68225873FA3C347 (frame_id), INDEX IDX_A68225875EEADD3B (time_id), INDEX IDX_A6822587EC8B7ADE (period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_evaluation_frame (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_evaluation_time (id INT AUTO_INCREMENT NOT NULL, evaluation_frame_id INT DEFAULT NULL, type_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_BC770F5132EDBA61 (evaluation_frame_id), INDEX IDX_BC770F51C54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_evaluation_time_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_95254E7E5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_period (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_section (id INT AUTO_INCREMENT NOT NULL, school_id INT DEFAULT NULL, section_id INT DEFAULT NULL, INDEX IDX_BF5C4877C32A47EE (school_id), INDEX IDX_BF5C4877D823E37A (section_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE section (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE section_category (id INT AUTO_INCREMENT NOT NULL, section_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_9621439DD823E37A (section_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE section_category_subject (id INT AUTO_INCREMENT NOT NULL, section_category_id INT DEFAULT NULL, section_category_subject_group_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, INDEX IDX_DC5615E04B7E29D (section_category_id), INDEX IDX_DC5615E0FB00225A (section_category_subject_group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE section_category_subject_group (id INT AUTO_INCREMENT NOT NULL, section_category_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, INDEX IDX_334937034B7E29D (section_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE student_attendance (id INT AUTO_INCREMENT NOT NULL, student_id INT DEFAULT NULL, school_class_id INT DEFAULT NULL, abscence INT NOT NULL, INDEX IDX_803CE070CB944F1A (student_id), INDEX IDX_803CE07014463F54 (school_class_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE student_class (id INT AUTO_INCREMENT NOT NULL, student_id INT DEFAULT NULL, school_class_id INT DEFAULT NULL, period_id INT DEFAULT NULL, INDEX IDX_657C6002CB944F1A (student_id), INDEX IDX_657C600214463F54 (school_class_id), INDEX IDX_657C6002EC8B7ADE (period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE student_note (id INT AUTO_INCREMENT NOT NULL, student_id INT DEFAULT NULL, school_class_id INT DEFAULT NULL, note DOUBLE PRECISION DEFAULT NULL, INDEX IDX_F09E81CCCB944F1A (student_id), INDEX IDX_F09E81CC14463F54 (school_class_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subject_grade (id INT AUTO_INCREMENT NOT NULL, evaluation_id INT DEFAULT NULL, subject_id INT DEFAULT NULL, s_class_id INT DEFAULT NULL, period_id INT DEFAULT NULL, created_at DATETIME NOT NULL, student_ids_and_grades LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', uploaded_at DATETIME DEFAULT NULL, INDEX IDX_48C96FEC456C5646 (evaluation_id), INDEX IDX_48C96FEC23EDC87 (subject_id), INDEX IDX_48C96FECDC3D0C33 (s_class_id), INDEX IDX_48C96FECEC8B7ADE (period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subject_group (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, class_id INT NOT NULL, period_id INT NOT NULL, pos_order INT NOT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_7C53851DC32A47EE (school_id), INDEX IDX_7C53851DEA000B10 (class_id), INDEX IDX_7C53851DEC8B7ADE (period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subjects_modules (id INT AUTO_INCREMENT NOT NULL, module_name VARCHAR(255) NOT NULL, module_slug VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_6479375E41F3B0A (module_name), UNIQUE INDEX UNIQ_647937522A1DE6E (module_slug), UNIQUE INDEX UNIQ_6479375E41F3B0A22A1DE6E (module_name, module_slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher_class (id INT AUTO_INCREMENT NOT NULL, teacher_id INT DEFAULT NULL, school_class_id INT DEFAULT NULL, period_id INT DEFAULT NULL, INDEX IDX_BCB4A5C241807E1D (teacher_id), INDEX IDX_BCB4A5C214463F54 (school_class_id), INDEX IDX_BCB4A5C2EC8B7ADE (period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, school_id INT DEFAULT NULL, tutor_id INT DEFAULT NULL, username VARCHAR(180) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, address LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, enabled TINYINT(1) NOT NULL, full_name VARCHAR(255) NOT NULL, login_at DATETIME DEFAULT NULL, capacity LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', infos LONGTEXT DEFAULT NULL, gender VARCHAR(10) NOT NULL, repeated TINYINT(1) NOT NULL, registration_number VARCHAR(255) DEFAULT NULL, date_of_birth DATE DEFAULT NULL, religion VARCHAR(255) DEFAULT NULL, place_of_birth VARCHAR(255) DEFAULT NULL, photo VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D64938CEDFBE (registration_number), INDEX IDX_8D93D649C32A47EE (school_id), INDEX IDX_8D93D649208F64F1 (tutor_id), UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_base_configuration (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, school_id INT NOT NULL, class_list LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', section_list LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', INDEX IDX_811D7695A76ED395 (user_id), INDEX IDX_811D7695C32A47EE (school_id), UNIQUE INDEX unique_user_school (user_id, school_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EBC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EB14463F54 FOREIGN KEY (school_class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EB9DC4B963 FOREIGN KEY (school_period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EBCB944F1A FOREIGN KEY (student_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE admission_reductions ADD CONSTRAINT FK_BA9FE4EB8373D28E FOREIGN KEY (reduction_modal_id) REFERENCES school_class_payment_modals (id)');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT FK_42B3F1CB23EDC87 FOREIGN KEY (subject_id) REFERENCES school_class_subject (id)');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT FK_42B3F1CBEA000B10 FOREIGN KEY (class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT FK_42B3F1CBEC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT FK_42B3F1CBAFC2B591 FOREIGN KEY (module_id) REFERENCES subjects_modules (id)');
        $this->addSql('ALTER TABLE class_subject_module ADD CONSTRAINT FK_42B3F1CBC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575CB944F1A FOREIGN KEY (student_id) REFERENCES student_class (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575A4748E19 FOREIGN KEY (class_subject_module_id) REFERENCES class_subject_module (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A5755EEADD3B FOREIGN KEY (time_id) REFERENCES school_evaluation_time (id)');
        $this->addSql('ALTER TABLE modalities_subscriptions ADD CONSTRAINT FK_6582079CCB944F1A FOREIGN KEY (student_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE modalities_subscriptions ADD CONSTRAINT FK_6582079C14463F54 FOREIGN KEY (school_class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE modalities_subscriptions ADD CONSTRAINT FK_6582079C9DC4B963 FOREIGN KEY (school_period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE modalities_subscriptions ADD CONSTRAINT FK_6582079CCC33534F FOREIGN KEY (payment_modal_id) REFERENCES school_class_payment_modals (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DF675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D9C6BD325 FOREIGN KEY (fees_id) REFERENCES fees (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABBAB45AECA FOREIGN KEY (fee_id) REFERENCES fees (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABBB069795C FOREIGN KEY (registration_base_config_id) REFERENCES registration_card_base_config (id)');
        $this->addSql('ALTER TABLE school_class ADD CONSTRAINT FK_33B1AF85C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_class ADD CONSTRAINT FK_33B1AF85EC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE school_class ADD CONSTRAINT FK_33B1AF854B7E29D FOREIGN KEY (section_category_id) REFERENCES section_category (id)');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA22314463F54 FOREIGN KEY (school_class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA223CB944F1A FOREIGN KEY (student_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA223C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA2239DC4B963 FOREIGN KEY (school_period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE school_class_admission_payments ADD CONSTRAINT FK_33FDA223CC33534F FOREIGN KEY (payment_modal_id) REFERENCES school_class_payment_modals (id)');
        $this->addSql('ALTER TABLE school_class_attendance ADD CONSTRAINT FK_410B528456C5646 FOREIGN KEY (evaluation_id) REFERENCES school_evaluation (id)');
        $this->addSql('ALTER TABLE school_class_attendance ADD CONSTRAINT FK_410B52814463F54 FOREIGN KEY (school_class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE school_class_grade ADD CONSTRAINT FK_EC8BBDB223EDC87 FOREIGN KEY (subject_id) REFERENCES school_class_subject (id)');
        $this->addSql('ALTER TABLE school_class_grade ADD CONSTRAINT FK_EC8BBDB2456C5646 FOREIGN KEY (evaluation_id) REFERENCES school_evaluation (id)');
        $this->addSql('ALTER TABLE school_class_grade ADD CONSTRAINT FK_EC8BBDB214463F54 FOREIGN KEY (school_class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE school_class_payment_modals ADD CONSTRAINT FK_662FC67914463F54 FOREIGN KEY (school_class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE school_class_payment_modals ADD CONSTRAINT FK_662FC6799DC4B963 FOREIGN KEY (school_period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE school_class_payment_modals ADD CONSTRAINT FK_662FC679C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT FK_12A9F5B8C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT FK_12A9F5B814463F54 FOREIGN KEY (school_class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT FK_12A9F5B8EC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT FK_12A9F5B841807E1D FOREIGN KEY (teacher_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT FK_12A9F5B87A1E0799 FOREIGN KEY (section_category_subject_id) REFERENCES section_category_subject (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT FK_12A9F5B888ED1A1 FOREIGN KEY (school_class_subject_group_id) REFERENCES school_class_subject_group (id)');
        $this->addSql('ALTER TABLE school_class_subject ADD CONSTRAINT FK_12A9F5B8FE54D947 FOREIGN KEY (group_id) REFERENCES subject_group (id)');
        $this->addSql('ALTER TABLE school_class_subject_group ADD CONSTRAINT FK_BE74C7FD14463F54 FOREIGN KEY (school_class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE school_class_subject_group ADD CONSTRAINT FK_BE74C7FDC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_class_subject_group ADD CONSTRAINT FK_BE74C7FDFB00225A FOREIGN KEY (section_category_subject_group_id) REFERENCES section_category_subject_group (id)');
        $this->addSql('ALTER TABLE school_evaluation ADD CONSTRAINT FK_A68225873FA3C347 FOREIGN KEY (frame_id) REFERENCES school_evaluation_frame (id)');
        $this->addSql('ALTER TABLE school_evaluation ADD CONSTRAINT FK_A68225875EEADD3B FOREIGN KEY (time_id) REFERENCES school_evaluation_time (id)');
        $this->addSql('ALTER TABLE school_evaluation ADD CONSTRAINT FK_A6822587EC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE school_evaluation_time ADD CONSTRAINT FK_BC770F5132EDBA61 FOREIGN KEY (evaluation_frame_id) REFERENCES school_evaluation_frame (id)');
        $this->addSql('ALTER TABLE school_evaluation_time ADD CONSTRAINT FK_BC770F51C54C8C93 FOREIGN KEY (type_id) REFERENCES school_evaluation_time_type (id)');
        $this->addSql('ALTER TABLE school_section ADD CONSTRAINT FK_BF5C4877C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_section ADD CONSTRAINT FK_BF5C4877D823E37A FOREIGN KEY (section_id) REFERENCES section (id)');
        $this->addSql('ALTER TABLE section_category ADD CONSTRAINT FK_9621439DD823E37A FOREIGN KEY (section_id) REFERENCES section (id)');
        $this->addSql('ALTER TABLE section_category_subject ADD CONSTRAINT FK_DC5615E04B7E29D FOREIGN KEY (section_category_id) REFERENCES section_category (id)');
        $this->addSql('ALTER TABLE section_category_subject ADD CONSTRAINT FK_DC5615E0FB00225A FOREIGN KEY (section_category_subject_group_id) REFERENCES section_category_subject_group (id)');
        $this->addSql('ALTER TABLE section_category_subject_group ADD CONSTRAINT FK_334937034B7E29D FOREIGN KEY (section_category_id) REFERENCES section_category (id)');
        $this->addSql('ALTER TABLE student_attendance ADD CONSTRAINT FK_803CE070CB944F1A FOREIGN KEY (student_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE student_attendance ADD CONSTRAINT FK_803CE07014463F54 FOREIGN KEY (school_class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE student_class ADD CONSTRAINT FK_657C6002CB944F1A FOREIGN KEY (student_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE student_class ADD CONSTRAINT FK_657C600214463F54 FOREIGN KEY (school_class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE student_class ADD CONSTRAINT FK_657C6002EC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE student_note ADD CONSTRAINT FK_F09E81CCCB944F1A FOREIGN KEY (student_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE student_note ADD CONSTRAINT FK_F09E81CC14463F54 FOREIGN KEY (school_class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE subject_grade ADD CONSTRAINT FK_48C96FEC456C5646 FOREIGN KEY (evaluation_id) REFERENCES school_evaluation (id)');
        $this->addSql('ALTER TABLE subject_grade ADD CONSTRAINT FK_48C96FEC23EDC87 FOREIGN KEY (subject_id) REFERENCES section_category_subject (id)');
        $this->addSql('ALTER TABLE subject_grade ADD CONSTRAINT FK_48C96FECDC3D0C33 FOREIGN KEY (s_class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE subject_grade ADD CONSTRAINT FK_48C96FECEC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE subject_group ADD CONSTRAINT FK_7C53851DC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE subject_group ADD CONSTRAINT FK_7C53851DEA000B10 FOREIGN KEY (class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE subject_group ADD CONSTRAINT FK_7C53851DEC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE teacher_class ADD CONSTRAINT FK_BCB4A5C241807E1D FOREIGN KEY (teacher_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE teacher_class ADD CONSTRAINT FK_BCB4A5C214463F54 FOREIGN KEY (school_class_id) REFERENCES school_class (id)');
        $this->addSql('ALTER TABLE teacher_class ADD CONSTRAINT FK_BCB4A5C2EC8B7ADE FOREIGN KEY (period_id) REFERENCES school_period (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D649C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D649208F64F1 FOREIGN KEY (tutor_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE user_base_configuration ADD CONSTRAINT FK_811D7695A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE user_base_configuration ADD CONSTRAINT FK_811D7695C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EBC32A47EE');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EB14463F54');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EB9DC4B963');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EBCB944F1A');
        $this->addSql('ALTER TABLE admission_reductions DROP FOREIGN KEY FK_BA9FE4EB8373D28E');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY FK_42B3F1CB23EDC87');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY FK_42B3F1CBEA000B10');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY FK_42B3F1CBEC8B7ADE');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY FK_42B3F1CBAFC2B591');
        $this->addSql('ALTER TABLE class_subject_module DROP FOREIGN KEY FK_42B3F1CBC32A47EE');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A575CB944F1A');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A575A4748E19');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A5755EEADD3B');
        $this->addSql('ALTER TABLE modalities_subscriptions DROP FOREIGN KEY FK_6582079CCB944F1A');
        $this->addSql('ALTER TABLE modalities_subscriptions DROP FOREIGN KEY FK_6582079C14463F54');
        $this->addSql('ALTER TABLE modalities_subscriptions DROP FOREIGN KEY FK_6582079C9DC4B963');
        $this->addSql('ALTER TABLE modalities_subscriptions DROP FOREIGN KEY FK_6582079CCC33534F');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840DF675F31B');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D9C6BD325');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABBAB45AECA');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABBB069795C');
        $this->addSql('ALTER TABLE school_class DROP FOREIGN KEY FK_33B1AF85C32A47EE');
        $this->addSql('ALTER TABLE school_class DROP FOREIGN KEY FK_33B1AF85EC8B7ADE');
        $this->addSql('ALTER TABLE school_class DROP FOREIGN KEY FK_33B1AF854B7E29D');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA22314463F54');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA223CB944F1A');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA223C32A47EE');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA2239DC4B963');
        $this->addSql('ALTER TABLE school_class_admission_payments DROP FOREIGN KEY FK_33FDA223CC33534F');
        $this->addSql('ALTER TABLE school_class_attendance DROP FOREIGN KEY FK_410B528456C5646');
        $this->addSql('ALTER TABLE school_class_attendance DROP FOREIGN KEY FK_410B52814463F54');
        $this->addSql('ALTER TABLE school_class_grade DROP FOREIGN KEY FK_EC8BBDB223EDC87');
        $this->addSql('ALTER TABLE school_class_grade DROP FOREIGN KEY FK_EC8BBDB2456C5646');
        $this->addSql('ALTER TABLE school_class_grade DROP FOREIGN KEY FK_EC8BBDB214463F54');
        $this->addSql('ALTER TABLE school_class_payment_modals DROP FOREIGN KEY FK_662FC67914463F54');
        $this->addSql('ALTER TABLE school_class_payment_modals DROP FOREIGN KEY FK_662FC6799DC4B963');
        $this->addSql('ALTER TABLE school_class_payment_modals DROP FOREIGN KEY FK_662FC679C32A47EE');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY FK_12A9F5B8C32A47EE');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY FK_12A9F5B814463F54');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY FK_12A9F5B8EC8B7ADE');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY FK_12A9F5B841807E1D');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY FK_12A9F5B87A1E0799');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY FK_12A9F5B888ED1A1');
        $this->addSql('ALTER TABLE school_class_subject DROP FOREIGN KEY FK_12A9F5B8FE54D947');
        $this->addSql('ALTER TABLE school_class_subject_group DROP FOREIGN KEY FK_BE74C7FD14463F54');
        $this->addSql('ALTER TABLE school_class_subject_group DROP FOREIGN KEY FK_BE74C7FDC32A47EE');
        $this->addSql('ALTER TABLE school_class_subject_group DROP FOREIGN KEY FK_BE74C7FDFB00225A');
        $this->addSql('ALTER TABLE school_evaluation DROP FOREIGN KEY FK_A68225873FA3C347');
        $this->addSql('ALTER TABLE school_evaluation DROP FOREIGN KEY FK_A68225875EEADD3B');
        $this->addSql('ALTER TABLE school_evaluation DROP FOREIGN KEY FK_A6822587EC8B7ADE');
        $this->addSql('ALTER TABLE school_evaluation_time DROP FOREIGN KEY FK_BC770F5132EDBA61');
        $this->addSql('ALTER TABLE school_evaluation_time DROP FOREIGN KEY FK_BC770F51C54C8C93');
        $this->addSql('ALTER TABLE school_section DROP FOREIGN KEY FK_BF5C4877C32A47EE');
        $this->addSql('ALTER TABLE school_section DROP FOREIGN KEY FK_BF5C4877D823E37A');
        $this->addSql('ALTER TABLE section_category DROP FOREIGN KEY FK_9621439DD823E37A');
        $this->addSql('ALTER TABLE section_category_subject DROP FOREIGN KEY FK_DC5615E04B7E29D');
        $this->addSql('ALTER TABLE section_category_subject DROP FOREIGN KEY FK_DC5615E0FB00225A');
        $this->addSql('ALTER TABLE section_category_subject_group DROP FOREIGN KEY FK_334937034B7E29D');
        $this->addSql('ALTER TABLE student_attendance DROP FOREIGN KEY FK_803CE070CB944F1A');
        $this->addSql('ALTER TABLE student_attendance DROP FOREIGN KEY FK_803CE07014463F54');
        $this->addSql('ALTER TABLE student_class DROP FOREIGN KEY FK_657C6002CB944F1A');
        $this->addSql('ALTER TABLE student_class DROP FOREIGN KEY FK_657C600214463F54');
        $this->addSql('ALTER TABLE student_class DROP FOREIGN KEY FK_657C6002EC8B7ADE');
        $this->addSql('ALTER TABLE student_note DROP FOREIGN KEY FK_F09E81CCCB944F1A');
        $this->addSql('ALTER TABLE student_note DROP FOREIGN KEY FK_F09E81CC14463F54');
        $this->addSql('ALTER TABLE subject_grade DROP FOREIGN KEY FK_48C96FEC456C5646');
        $this->addSql('ALTER TABLE subject_grade DROP FOREIGN KEY FK_48C96FEC23EDC87');
        $this->addSql('ALTER TABLE subject_grade DROP FOREIGN KEY FK_48C96FECDC3D0C33');
        $this->addSql('ALTER TABLE subject_grade DROP FOREIGN KEY FK_48C96FECEC8B7ADE');
        $this->addSql('ALTER TABLE subject_group DROP FOREIGN KEY FK_7C53851DC32A47EE');
        $this->addSql('ALTER TABLE subject_group DROP FOREIGN KEY FK_7C53851DEA000B10');
        $this->addSql('ALTER TABLE subject_group DROP FOREIGN KEY FK_7C53851DEC8B7ADE');
        $this->addSql('ALTER TABLE teacher_class DROP FOREIGN KEY FK_BCB4A5C241807E1D');
        $this->addSql('ALTER TABLE teacher_class DROP FOREIGN KEY FK_BCB4A5C214463F54');
        $this->addSql('ALTER TABLE teacher_class DROP FOREIGN KEY FK_BCB4A5C2EC8B7ADE');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D649C32A47EE');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D649208F64F1');
        $this->addSql('ALTER TABLE user_base_configuration DROP FOREIGN KEY FK_811D7695A76ED395');
        $this->addSql('ALTER TABLE user_base_configuration DROP FOREIGN KEY FK_811D7695C32A47EE');
        $this->addSql('DROP TABLE admission_reductions');
        $this->addSql('DROP TABLE class_subject_module');
        $this->addSql('DROP TABLE core_update');
        $this->addSql('DROP TABLE evaluation');
        $this->addSql('DROP TABLE fees');
        $this->addSql('DROP TABLE modalities_subscriptions');
        $this->addSql('DROP TABLE operation_logs');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE registration_card_base_config');
        $this->addSql('DROP TABLE school');
        $this->addSql('DROP TABLE school_class');
        $this->addSql('DROP TABLE school_class_admission_payments');
        $this->addSql('DROP TABLE school_class_attendance');
        $this->addSql('DROP TABLE school_class_grade');
        $this->addSql('DROP TABLE school_class_payment_modals');
        $this->addSql('DROP TABLE school_class_subject');
        $this->addSql('DROP TABLE school_class_subject_group');
        $this->addSql('DROP TABLE school_evaluation');
        $this->addSql('DROP TABLE school_evaluation_frame');
        $this->addSql('DROP TABLE school_evaluation_time');
        $this->addSql('DROP TABLE school_evaluation_time_type');
        $this->addSql('DROP TABLE school_period');
        $this->addSql('DROP TABLE school_section');
        $this->addSql('DROP TABLE section');
        $this->addSql('DROP TABLE section_category');
        $this->addSql('DROP TABLE section_category_subject');
        $this->addSql('DROP TABLE section_category_subject_group');
        $this->addSql('DROP TABLE student_attendance');
        $this->addSql('DROP TABLE student_class');
        $this->addSql('DROP TABLE student_note');
        $this->addSql('DROP TABLE subject_grade');
        $this->addSql('DROP TABLE subject_group');
        $this->addSql('DROP TABLE subjects_modules');
        $this->addSql('DROP TABLE teacher_class');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE user_base_configuration');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
