server {
    listen 80;
    server_name _;
    root /var/www/public;
    index index.php index.html;

    # Logs
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location ~ ^/build/ {
        # Si le fichier existe, Nginx le sert immédiatement.
        try_files $uri =404; 
        
        # Ajout optionnel pour améliorer la performance du cache navigateur
        expires max; 
        access_log off;
    }
    
    # Static files
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # PHP handling
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        
        fastcgi_index index.php;
        fastcgi_hide_header X-Powered-By;
        fastcgi_read_timeout 300;
    }

    # Deny access to hidden files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Deny access to sensitive files
    location ~ /(composer\.json|composer\.lock|README\.md|\.git) {
        deny all;
        access_log off;
        log_not_found off;
    }
}