[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.log
stderr_logfile=/var/log/php-fpm_error.log
user=www

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx.log
stderr_logfile=/var/log/nginx_error.log
user=www

[program:messenger-worker-1]
command=php /var/www/bin/console messenger:consume async --time-limit=3600 --memory-limit=512M
numprocs=1
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
startretries=3
user=www
stdout_logfile=/var/log/messenger_worker.log
stderr_logfile=/var/log/messenger_worker_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
environment=APP_ENV=dev

[program:messenger-worker-2]
command=php /var/www/bin/console messenger:consume async --time-limit=3600 --memory-limit=512M
numprocs=1
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
startretries=3
user=www
stdout_logfile=/var/log/messenger_worker2.log
stderr_logfile=/var/log/messenger_worker2_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
environment=APP_ENV=dev

[program:messenger-worker-3]
command=php /var/www/bin/console messenger:consume async --time-limit=3600 --memory-limit=512M
numprocs=1
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
startretries=3
user=www
stdout_logfile=/var/log/messenger_worker3.log
stderr_logfile=/var/log/messenger_worker3_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
environment=APP_ENV=dev